import {query} from './db';

export type LiveAssetRow={id:string;asset_code:string;asset_type:string;name:string;model:string|null;serial_number:string|null;location_label:string|null;status:string;qr_token:string;specifications:Record<string,unknown>;installed_at:Date|null;commissioned_at:Date|null;warranty_expires_at:Date|null;project_code:string;project_name:string;site_name:string;system_name:string|null;manufacturer_name:string|null;latest_event_id:string|null;latest_event_type:string|null;latest_event_status:string|null;ledger_network:string|null;ledger_tx_hash:string|null;ledger_block_height:string|null;anchored_at:Date|null;};

export type LiveProjectRow={id:string;project_code:string;name:string;client_name:string|null;address:string|null;status:string;site_count:number;asset_count:number;verified_asset_count:number;verified_event_count:number;pending_event_count:number};
export type LiveSiteRow={id:string;name:string;address:string|null;project_id:string;project_code:string;project_name:string;system_count:number;asset_count:number;verified_event_count:number;pending_event_count:number};
export type LiveEvidenceRow={id:string;file_name:string|null;kind:string;sha256:string;visibility:string;captured_at:Date|null;asset_id:string;asset_code:string;asset_name:string;project_code:string;project_name:string;event_type:string;event_status:string;ledger_block_height:string|null};
export type LiveMaintenanceRow={id:string;event_type:string;status:string;occurred_at:Date;asset_id:string;asset_code:string;asset_name:string;site_name:string;project_code:string;project_name:string;evidence_count:number;ledger_block_height:string|null;anchored_at:Date|null};
export type LiveProvenanceRow={id:string;asset_code:string;name:string;serial_number:string|null;manufacturer_name:string|null;project_code:string;project_name:string;verified_event_types:string[];latest_event_type:string|null;ledger_block_height:string|null;anchored_at:Date|null};

export async function liveAssets(organizationId:string,projectIds:string[]){if(!projectIds.length)return[];const r=await query<LiveAssetRow>(`SELECT a.id,a.asset_code,a.asset_type,a.name,a.model,a.serial_number,a.location_label,a.status,a.qr_token::text,a.specifications,a.installed_at,a.commissioned_at,a.warranty_expires_at,p.project_code,p.name project_name,si.name site_name,sy.name system_name,m.name manufacturer_name,le.id::text latest_event_id,le.event_type::text latest_event_type,le.status::text latest_event_status,le.ledger_network,le.ledger_tx_hash,le.ledger_block_height::text,le.anchored_at FROM assets a JOIN projects p ON p.id=a.project_id JOIN sites si ON si.id=a.site_id LEFT JOIN systems sy ON sy.id=a.system_id LEFT JOIN manufacturers m ON m.id=a.manufacturer_id LEFT JOIN LATERAL (SELECT x.* FROM lifecycle_events x WHERE x.asset_id=a.id AND x.organization_id=a.organization_id AND x.status='VERIFIED' ORDER BY x.occurred_at DESC,x.anchored_at DESC NULLS LAST LIMIT 1) le ON true WHERE a.organization_id=$1 AND a.project_id=ANY($2::uuid[]) ORDER BY COALESCE(le.anchored_at,a.created_at) DESC LIMIT 500`,[organizationId,projectIds]);return r.rows}

export async function liveAsset(organizationId:string,projectIds:string[],identifier:string){if(!projectIds.length)return null;const r=await query<LiveAssetRow>(`SELECT a.id,a.asset_code,a.asset_type,a.name,a.model,a.serial_number,a.location_label,a.status,a.qr_token::text,a.specifications,a.installed_at,a.commissioned_at,a.warranty_expires_at,p.project_code,p.name project_name,si.name site_name,sy.name system_name,m.name manufacturer_name,le.id::text latest_event_id,le.event_type::text latest_event_type,le.status::text latest_event_status,le.ledger_network,le.ledger_tx_hash,le.ledger_block_height::text,le.anchored_at FROM assets a JOIN projects p ON p.id=a.project_id JOIN sites si ON si.id=a.site_id LEFT JOIN systems sy ON sy.id=a.system_id LEFT JOIN manufacturers m ON m.id=a.manufacturer_id LEFT JOIN LATERAL (SELECT x.* FROM lifecycle_events x WHERE x.asset_id=a.id AND x.organization_id=a.organization_id AND x.status='VERIFIED' ORDER BY x.occurred_at DESC,x.anchored_at DESC NULLS LAST LIMIT 1) le ON true WHERE a.organization_id=$1 AND a.project_id=ANY($2::uuid[]) AND (a.id::text=$3 OR a.asset_code=$3) LIMIT 1`,[organizationId,projectIds,identifier]);return r.rows[0]||null}

export async function assetLifecycle(organizationId:string,assetId:string){const r=await query<any>(`SELECT le.id::text,le.event_type::text,le.status::text,le.occurred_at,le.payload_sha256,le.evidence_package_sha256,le.ledger_network,le.ledger_tx_hash,le.ledger_block_height::text,le.anchored_at,performer.display_name performed_by_name,approver.display_name approved_by_name,(SELECT count(*)::int FROM evidence ev WHERE ev.lifecycle_event_id=le.id AND ev.organization_id=le.organization_id) evidence_count FROM lifecycle_events le LEFT JOIN users performer ON performer.id=le.performed_by LEFT JOIN users approver ON approver.id=le.approved_by WHERE le.organization_id=$1 AND le.asset_id=$2 ORDER BY le.occurred_at DESC`,[organizationId,assetId]);return r.rows}

export async function internalEvidence(organizationId:string,assetId:string){const r=await query<any>(`SELECT ev.id::text,ev.file_name,ev.kind,ev.sha256,ev.visibility,ev.captured_at FROM evidence ev WHERE ev.organization_id=$1 AND ev.asset_id=$2 ORDER BY ev.captured_at DESC NULLS LAST,ev.created_at DESC`,[organizationId,assetId]);return r.rows}

export async function liveProjects(organizationId:string,projectIds:string[]){if(!projectIds.length)return[];const r=await query<LiveProjectRow>(`SELECT p.id::text,p.project_code,p.name,p.client_name,p.address,p.status,(SELECT COUNT(*)::int FROM sites si WHERE si.organization_id=p.organization_id AND si.project_id=p.id) site_count,(SELECT COUNT(*)::int FROM assets a WHERE a.organization_id=p.organization_id AND a.project_id=p.id) asset_count,(SELECT COUNT(DISTINCT le.asset_id)::int FROM lifecycle_events le WHERE le.organization_id=p.organization_id AND le.project_id=p.id AND le.status='VERIFIED') verified_asset_count,(SELECT COUNT(*)::int FROM lifecycle_events le WHERE le.organization_id=p.organization_id AND le.project_id=p.id AND le.status='VERIFIED') verified_event_count,(SELECT COUNT(*)::int FROM lifecycle_events le WHERE le.organization_id=p.organization_id AND le.project_id=p.id AND le.status='SUBMITTED') pending_event_count FROM projects p WHERE p.organization_id=$1 AND p.id=ANY($2::uuid[]) ORDER BY p.created_at DESC`,[organizationId,projectIds]);return r.rows}

export async function liveSites(organizationId:string,projectIds:string[]){if(!projectIds.length)return[];const r=await query<LiveSiteRow>(`SELECT si.id::text,si.name,si.address,si.project_id::text,p.project_code,p.name project_name,(SELECT COUNT(*)::int FROM systems sy WHERE sy.organization_id=si.organization_id AND sy.site_id=si.id) system_count,(SELECT COUNT(*)::int FROM assets a WHERE a.organization_id=si.organization_id AND a.site_id=si.id) asset_count,(SELECT COUNT(*)::int FROM lifecycle_events le JOIN assets a ON a.id=le.asset_id WHERE le.organization_id=si.organization_id AND a.site_id=si.id AND le.status='VERIFIED') verified_event_count,(SELECT COUNT(*)::int FROM lifecycle_events le JOIN assets a ON a.id=le.asset_id WHERE le.organization_id=si.organization_id AND a.site_id=si.id AND le.status='SUBMITTED') pending_event_count FROM sites si JOIN projects p ON p.id=si.project_id WHERE si.organization_id=$1 AND si.project_id=ANY($2::uuid[]) ORDER BY p.project_code,si.name`,[organizationId,projectIds]);return r.rows}

export async function liveEvidence(organizationId:string,projectIds:string[]){if(!projectIds.length)return[];const r=await query<LiveEvidenceRow>(`SELECT ev.id::text,ev.file_name,ev.kind,ev.sha256,ev.visibility,ev.captured_at,a.id::text asset_id,a.asset_code,a.name asset_name,p.project_code,p.name project_name,le.event_type::text,le.status::text event_status,le.ledger_block_height::text FROM evidence ev JOIN assets a ON a.id=ev.asset_id AND a.organization_id=ev.organization_id JOIN projects p ON p.id=a.project_id JOIN lifecycle_events le ON le.id=ev.lifecycle_event_id AND le.organization_id=ev.organization_id WHERE ev.organization_id=$1 AND a.project_id=ANY($2::uuid[]) ORDER BY ev.captured_at DESC NULLS LAST,ev.created_at DESC LIMIT 500`,[organizationId,projectIds]);return r.rows}

export async function liveMaintenance(organizationId:string,projectIds:string[]){if(!projectIds.length)return[];const r=await query<LiveMaintenanceRow>(`SELECT le.id::text,le.event_type::text,le.status::text,le.occurred_at,a.id::text asset_id,a.asset_code,a.name asset_name,si.name site_name,p.project_code,p.name project_name,(SELECT COUNT(*)::int FROM evidence ev WHERE ev.organization_id=le.organization_id AND ev.lifecycle_event_id=le.id) evidence_count,le.ledger_block_height::text,le.anchored_at FROM lifecycle_events le JOIN assets a ON a.id=le.asset_id JOIN sites si ON si.id=a.site_id JOIN projects p ON p.id=le.project_id WHERE le.organization_id=$1 AND le.project_id=ANY($2::uuid[]) AND le.event_type IN ('INSPECT','TEST','MAINTAIN','REPAIR','REPLACE') ORDER BY le.occurred_at DESC LIMIT 300`,[organizationId,projectIds]);return r.rows}

export async function liveProvenance(organizationId:string,projectIds:string[]){if(!projectIds.length)return[];const r=await query<LiveProvenanceRow>(`SELECT a.id::text,a.asset_code,a.name,a.serial_number,m.name manufacturer_name,p.project_code,p.name project_name,COALESCE(ARRAY_REMOVE(ARRAY_AGG(DISTINCT CASE WHEN le.status='VERIFIED' THEN le.event_type::text END),NULL),ARRAY[]::text[]) verified_event_types,latest.event_type::text latest_event_type,latest.ledger_block_height::text,latest.anchored_at FROM assets a JOIN projects p ON p.id=a.project_id LEFT JOIN manufacturers m ON m.id=a.manufacturer_id LEFT JOIN lifecycle_events le ON le.asset_id=a.id AND le.organization_id=a.organization_id LEFT JOIN LATERAL (SELECT x.event_type,x.ledger_block_height,x.anchored_at FROM lifecycle_events x WHERE x.organization_id=a.organization_id AND x.asset_id=a.id AND x.status='VERIFIED' ORDER BY x.occurred_at DESC,x.anchored_at DESC NULLS LAST LIMIT 1) latest ON true WHERE a.organization_id=$1 AND a.project_id=ANY($2::uuid[]) GROUP BY a.id,m.name,p.project_code,p.name,latest.event_type,latest.ledger_block_height,latest.anchored_at ORDER BY latest.anchored_at DESC NULLS LAST,a.created_at DESC LIMIT 500`,[organizationId,projectIds]);return r.rows}

export async function liveOverview(organizationId:string,projectIds:string[]){
 if(!projectIds.length)return{projectCount:0,siteCount:0,assetCount:0,verifiedAssetCount:0,verifiedEventCount:0,pendingEventCount:0,evidenceCount:0,recent:[] as any[]};
 const [p,si,a,va,ve,pe,ev,recent]=await Promise.all([
  query<{n:number}>(`SELECT COUNT(*)::int n FROM projects WHERE organization_id=$1 AND id=ANY($2::uuid[])`,[organizationId,projectIds]),
  query<{n:number}>(`SELECT COUNT(*)::int n FROM sites WHERE organization_id=$1 AND project_id=ANY($2::uuid[])`,[organizationId,projectIds]),
  query<{n:number}>(`SELECT COUNT(*)::int n FROM assets WHERE organization_id=$1 AND project_id=ANY($2::uuid[])`,[organizationId,projectIds]),
  query<{n:number}>(`SELECT COUNT(DISTINCT asset_id)::int n FROM lifecycle_events WHERE organization_id=$1 AND project_id=ANY($2::uuid[]) AND status='VERIFIED'`,[organizationId,projectIds]),
  query<{n:number}>(`SELECT COUNT(*)::int n FROM lifecycle_events WHERE organization_id=$1 AND project_id=ANY($2::uuid[]) AND status='VERIFIED'`,[organizationId,projectIds]),
  query<{n:number}>(`SELECT COUNT(*)::int n FROM lifecycle_events WHERE organization_id=$1 AND project_id=ANY($2::uuid[]) AND status='SUBMITTED'`,[organizationId,projectIds]),
  query<{n:number}>(`SELECT COUNT(*)::int n FROM evidence ev JOIN assets a ON a.id=ev.asset_id WHERE ev.organization_id=$1 AND a.project_id=ANY($2::uuid[])`,[organizationId,projectIds]),
  query<any>(`SELECT le.id::text,le.event_type::text,le.status::text,le.occurred_at,le.ledger_block_height::text,a.id::text asset_id,a.asset_code,a.name asset_name,p.project_code,p.name project_name,u.display_name actor_name FROM lifecycle_events le JOIN assets a ON a.id=le.asset_id JOIN projects p ON p.id=le.project_id LEFT JOIN users u ON u.id=le.performed_by WHERE le.organization_id=$1 AND le.project_id=ANY($2::uuid[]) ORDER BY le.occurred_at DESC LIMIT 12`,[organizationId,projectIds])
 ]);
 return{projectCount:p.rows[0]?.n||0,siteCount:si.rows[0]?.n||0,assetCount:a.rows[0]?.n||0,verifiedAssetCount:va.rows[0]?.n||0,verifiedEventCount:ve.rows[0]?.n||0,pendingEventCount:pe.rows[0]?.n||0,evidenceCount:ev.rows[0]?.n||0,recent:recent.rows};
}

export async function recentChain(){const [state,blocks]=await Promise.all([query<any>(`SELECT chain_id,height::text,latest_block_hash,genesis_hash,updated_at FROM sv_chain_state WHERE chain_id=$1`,[process.env.STRATUM_CHAIN_ID||'stratum-devnet-1']),query<any>(`SELECT b.height::text,b.block_hash,b.prev_hash,b.tx_hash,b.proposer_validator_id,b.finalized_at,b.votes_json,t.record_id,t.event_type,t.asset_id,t.evidence_hash,t.payload_hash FROM sv_chain_blocks b LEFT JOIN sv_chain_transactions t ON t.chain_id=b.chain_id AND t.tx_hash=b.tx_hash WHERE b.chain_id=$1 ORDER BY b.height DESC LIMIT 25`,[process.env.STRATUM_CHAIN_ID||'stratum-devnet-1'])]);return{state:state.rows[0]||null,blocks:blocks.rows}}
