import Link from 'next/link';
import {accessibleProjectIds} from '@/lib/server/access';
import {liveOverview} from '@/lib/server/live-views';
import {optionalPageSession} from '@/lib/server/page-auth';
export const dynamic='force-dynamic';

const date=(d:Date|string)=>new Date(d).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});

export default async function Home(){
 const session=await optionalPageSession();
 if(!session)return <>
  <div className="topline"><div><div className="eyebrow">Infrastructure Trust Operating System</div><h1 className="title">Know what exists. Know what happened. Prove it.</h1><div className="subtitle">STRATUM Twin represents physical infrastructure. STRATUM Verified captures identity, evidence, lifecycle and independent approval. Digital Immutable Records (DIRs) preserve approved cryptographic proof without exposing private source files.</div></div><div className="badge">DIRs · {process.env.STRATUM_CHAIN_ID||'stratum-devnet-1'}</div></div>
  <section className="hero"><div className="card hero-copy"><div className="eyebrow">Physical → Digital → Verified</div><h2>One durable identity for every installed asset.</h2><p className="muted">Create an asset identity, record field work, attach server-hashed evidence, enforce independent approval and publish only the resulting proof to the DIR trust layer.</p><div className="button-row"><Link className="action" href="/login">Sign in to workspace</Link><Link className="ghost" href="/verify">Public verifier</Link></div></div><div className="card layer-visual"><div className="layer l1"><b>L1</b><span>Physical Infrastructure</span></div><div className="layer l2"><b>L2</b><span>STRATUM Twin</span></div><div className="layer l3"><b>L3</b><span>Operational Evidence</span></div><div className="layer l4"><b>L4</b><span>STRATUM Verified</span></div><div className="layer l5"><b>L5</b><span>Digital Immutable Records</span></div></div></section>
 </>;
 const projectIds=await accessibleProjectIds(session);const x=await liveOverview(session.organizationId,projectIds);const coverage=x.assetCount?Math.round(x.verifiedAssetCount/x.assetCount*100):0;
 return <>
  <div className="topline"><div><div className="eyebrow">Live Organization Workspace</div><h1 className="title">Infrastructure verification command center.</h1><div className="subtitle">Every metric below is calculated from the active organization and the projects available to your role. Demo portfolio counts are not used.</div></div><div className="badge">{session.role.replaceAll('_',' ')} · {x.projectCount} project{x.projectCount===1?'':'s'}</div></div>
  <section className="hero"><div className="card hero-copy"><div className="eyebrow">Register → Perform → Prove</div><h2>Advance assets through controlled lifecycle states.</h2><p className="muted">The workflow now gates each event against verified prerequisites, requires project-scoped authorization, hashes field evidence and separates performer from approver before finalization.</p><div className="button-row"><Link className="action" href="/workflows">Open operational workflow</Link><Link className="ghost" href="/assets">Asset passports</Link><Link className="ghost" href="/verify">Verify a record</Link></div></div><div className="card layer-visual"><div className="layer l1"><b>01</b><span>Asset identity</span></div><div className="layer l2"><b>02</b><span>Field lifecycle</span></div><div className="layer l3"><b>03</b><span>Evidence package</span></div><div className="layer l4"><b>04</b><span>Independent approval</span></div><div className="layer l5"><b>05</b><span>Finalized DIR proof</span></div></div></section>
  <section className="grid kpis"><div className="card"><div className="label">Tracked Assets</div><div className="metric">{x.assetCount.toLocaleString()}</div><div className="muted">Across {x.siteCount} sites</div></div><div className="card"><div className="label">Verified Assets</div><div className="metric">{x.verifiedAssetCount.toLocaleString()}</div><div className="muted">{coverage}% with at least one finalized proof</div></div><div className="card"><div className="label">Verified Lifecycle Events</div><div className="metric">{x.verifiedEventCount.toLocaleString()}</div><div className="muted">{x.evidenceCount.toLocaleString()} evidence fingerprints stored</div></div><div className="card"><div className="label">Pending Approvals</div><div className="metric">{x.pendingEventCount.toLocaleString()}</div><div className="muted">Submitted lifecycle records awaiting decision</div></div></section>
  <section className="card" style={{marginTop:16}}><div className="section-head"><div><div className="eyebrow">Live Activity</div><h2>Recent lifecycle stream</h2></div><Link className="ghost" href="/provenance">Full provenance</Link></div><div className="timeline">{x.recent.map((e:any)=><div className="event" key={e.id}><i className={`event-icon ${e.status==='VERIFIED'?'commission':''}`}>{e.status==='VERIFIED'?'✓':'●'}</i><div style={{flex:1}}><strong>{e.event_type} · {e.asset_code} · {e.asset_name}</strong><small>{e.project_code} · {e.actor_name||'Recorded actor'} · {date(e.occurred_at)}</small></div><span className={e.status==='VERIFIED'?'proof':'pending'}>{e.ledger_block_height?`DIR #${e.ledger_block_height}`:e.status}</span></div>)}{!x.recent.length&&<p className="muted">No lifecycle activity has been recorded in your accessible projects yet. Start in Operational Workflow.</p>}</div></section>
 </>;
}
