'use client';
import {FormEvent,useEffect,useState} from 'react';

type UserRow={id:string;email:string;display_name:string;is_active:boolean;last_login_at:string|null;created_at:string;role:string;session_version:number;active_signing_keys:number};
type EventRow={id:number;event_type:string;created_at:string;metadata:any;email?:string;display_name?:string;actor_email?:string};
type Session={userId:string;email:string;organizationId:string;role:string};
const roles=['SUPER_ADMIN','ORG_ADMIN','PROJECT_MANAGER','TECHNICIAN','INSPECTOR','CLIENT','VIEWER'];
const inputStyle={width:'100%',padding:'9px 10px',borderRadius:9,border:'1px solid #21405a',background:'#081723',color:'#eef6ff'} as const;
async function json(url:string,options?:RequestInit){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options?.headers||{})}});const x=await r.json();if(!r.ok)throw new Error(x.error||`Request failed (${r.status})`);return x}
export default function AdminConsole(){const [users,setUsers]=useState<UserRow[]>([]),[events,setEvents]=useState<EventRow[]>([]),[session,setSession]=useState<Session|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState('');
 async function refresh(){const [u,e]=await Promise.all([json('/api/admin/users'),json('/api/admin/security-events')]);setUsers(u.items||[]);setSession(u.session||null);setEvents(e.items||[])}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
 async function createUser(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy('create');setMessage('');const f=new FormData(e.currentTarget);try{await json('/api/admin/users',{method:'POST',body:JSON.stringify(Object.fromEntries(f.entries()))});e.currentTarget.reset();setMessage('User created and organization membership assigned.');await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}
 async function patch(userId:string,body:any){setBusy(userId);setMessage('');try{await json('/api/admin/users',{method:'PATCH',body:JSON.stringify({userId,...body})});setMessage('User security settings updated.');await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}
 return <div className="grid" style={{gap:16}}>{message&&<div className="card notice"><strong>Admin</strong><span>{message}</span></div>}
  <section className="card"><div className="section-head"><div><div className="eyebrow">Organization Identity</div><h2>Users & access</h2><p className="muted">Role changes, disablement and session revocation are enforced on the next protected request.</p></div><span className="badge">{session?.role||'ADMIN'}</span></div>
   <form onSubmit={createUser} style={{display:'grid',gridTemplateColumns:'1.2fr 1.2fr 1fr 1fr auto',gap:8,marginTop:14}}><input name="displayName" placeholder="Display name" required style={inputStyle}/><input name="email" type="email" placeholder="Email" required style={inputStyle}/><select name="role" defaultValue="VIEWER" style={inputStyle}>{roles.map(r=><option key={r}>{r}</option>)}</select><input name="password" type="password" minLength={12} placeholder="Temporary password" required style={inputStyle}/><button className="action" disabled={!!busy}>{busy==='create'?'Creating…':'Create user'}</button></form>
  </section>
  <section className="card table-card"><table className="table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Signing keys</th><th>Last login</th><th>Security actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.display_name||u.email}</strong><div className="muted">{u.email}</div></td><td><select value={u.role} onChange={e=>patch(u.id,{role:e.target.value})} disabled={!!busy} style={inputStyle}>{roles.map(r=><option key={r}>{r}</option>)}</select></td><td><span className={u.is_active?'proof':'pending'}>{u.is_active?'ACTIVE':'DISABLED'}</span></td><td><span className="mono">{u.active_signing_keys}</span></td><td className="muted">{u.last_login_at?new Date(u.last_login_at).toLocaleString():'Never'}</td><td><div className="button-row"><button className="ghost" disabled={!!busy||u.id===session?.userId} onClick={()=>patch(u.id,{isActive:!u.is_active})}>{u.is_active?'Disable':'Enable'}</button><button className="ghost" disabled={!!busy} onClick={()=>patch(u.id,{resetSessions:true})}>Revoke sessions</button></div></td></tr>)}</tbody></table></section>
  <section className="card"><div className="eyebrow">Security Activity</div><h2>Recent identity events</h2><div className="timeline">{events.map(e=><div className="event" key={e.id}><i className="event-icon">✓</i><div><strong>{e.event_type}</strong><small>{e.display_name||e.email||'System'} · actor {e.actor_email||'system'} · {new Date(e.created_at).toLocaleString()}</small></div></div>)}{!events.length&&<div className="muted">No security events recorded yet.</div>}</div></section>
 </div>}
