'use client';
import {useEffect,useMemo,useState} from 'react';
type Project={id:string;project_code:string;name:string;client_name?:string|null};
type Site={id:string;project_id?:string|null;name:string;project_name?:string|null};
type System={id:string;site_id:string;name:string;system_type?:string|null};
type Asset={id:string;project_id:string;site_id:string;system_id?:string|null;asset_code:string;name:string;serial_number?:string|null};
type Pending={id:string;project_id:string;asset_id:string;event_type:string;occurred_at:string;payload_sha256:string;asset_code:string;asset_name:string;project_code:string;project_name:string;performer_name?:string|null;performer_email?:string|null;performed_by_me:boolean;evidence_count:number};
type Session={userId:string;email:string;role:string};
const eventTypes=['REGISTER_ASSET','PROCURE','SHIP','TRANSFER_CUSTODY','RECEIVE','INSTALL','INSPECT','TEST','COMMISSION','ENERGIZE','MAINTAIN','REPAIR','REPLACE','DECOMMISSION'];
const inputStyle={width:'100%',padding:'10px 11px',borderRadius:10,border:'1px solid #21405a',background:'#081723',color:'#eef6ff'} as const;
const gridStyle={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10} as const;
async function json<T=any>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,{...options,headers:{...(options?.body instanceof FormData?{}:{'content-type':'application/json'}),...(options?.headers||{})}});const x=await r.json();if(!r.ok)throw new Error(x.error||`Request failed (${r.status})`);return x}
function b64(buf:ArrayBuffer){let s='';for(const x of new Uint8Array(buf))s+=String.fromCharCode(x);return btoa(s)}
export default function OperationsConsole(){
 const [projects,setProjects]=useState<Project[]>([]),[sites,setSites]=useState<Site[]>([]),[systems,setSystems]=useState<System[]>([]),[assets,setAssets]=useState<Asset[]>([]),[pending,setPending]=useState<Pending[]>([]),[session,setSession]=useState<Session|null>(null);
 const [busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const [projectId,setProjectId]=useState(''),[siteId,setSiteId]=useState(''),[systemId,setSystemId]=useState(''),[assetId,setAssetId]=useState(''),[eventType,setEventType]=useState('INSTALL'),[eventNotes,setEventNotes]=useState(''),[eventId,setEventId]=useState('');
 async function refresh(){const [p,si,sy,a,pe]=await Promise.all([json('/api/projects'),json('/api/sites'),json('/api/systems'),json('/api/assets'),json('/api/pending')]);setProjects(p.items||[]);setSites(si.items||[]);setSystems(sy.items||[]);setAssets(a.items||[]);setPending(pe.items||[]);setSession(pe.session||null)}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
 const filteredSites=useMemo(()=>sites.filter(s=>!projectId||s.project_id===projectId),[sites,projectId]);
 const filteredSystems=useMemo(()=>systems.filter(s=>!siteId||s.site_id===siteId),[systems,siteId]);
 const filteredAssets=useMemo(()=>assets.filter(a=>(!projectId||a.project_id===projectId)&&(!siteId||a.site_id===siteId)&&(!systemId||a.system_id===systemId)),[assets,projectId,siteId,systemId]);
 async function submitForm(e:React.FormEvent<HTMLFormElement>,url:string,label:string){e.preventDefault();setBusy(label);setMessage('');const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries());for(const k of Object.keys(body))if(body[k]==='')delete body[k];try{await json(url,{method:'POST',body:JSON.stringify(body)});setMessage(`${label} created.`);e.currentTarget.reset();await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}
 async function createLifecycle(){if(!assetId)return setMessage('Select an asset first.');const asset=assets.find(a=>a.id===assetId);if(!asset)return;setBusy('lifecycle');setMessage('');try{const x=await json('/api/lifecycle',{method:'POST',body:JSON.stringify({projectId:asset.project_id,assetId:eventId||assetId,eventType,payload:{notes:eventNotes,assetCode:asset.asset_code,source:'STRATUM Verified Operations Console'}})});setEventId(x.id);setMessage(`Lifecycle event ${x.id} submitted. Add evidence, then have an independent approver finalize it.`);await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}
 async function uploadEvidence(file:File|null){if(!file||!eventId||!assetId)return setMessage('Create a lifecycle event and select a file first.');setBusy('evidence');setMessage('');try{const bytes=await file.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');const fd=new FormData();fd.set('file',file);fd.set('lifecycleEventId',eventId);fd.set('assetId',assetId);fd.set('kind','FIELD_EVIDENCE');fd.set('visibility','PRIVATE');fd.set('sha256',digest);await json('/api/evidence/upload',{method:'POST',body:fd});setMessage(`Evidence stored and server-verified: ${digest}`);await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}
 async function approve(item:Pending){if(item.performed_by_me)return setMessage('Separation of duties: the performer cannot approve this event. Sign in as an independent inspector/project approver.');setBusy(item.id);setMessage('');try{const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const signature=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},keys.privateKey,new TextEncoder().encode(item.payload_sha256));const publicKeyJwk=await crypto.subtle.exportKey('jwk',keys.publicKey);const out=await json('/api/approvals',{method:'POST',body:JSON.stringify({lifecycleEventId:item.id,decision:'APPROVED',comment:'Approved from STRATUM Verified operations console',signature:b64(signature),publicKeyJwk})});setMessage(`Verified on ${out.receipt.network} · Block #${out.receipt.blockHeight} · ${out.receipt.txHash}`);await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}
 return <div className="grid" style={{gap:16}}>
  {message&&<div className="card notice"><strong>System</strong><span>{message}</span></div>}
  <section className="card"><div className="section-head"><div><div className="eyebrow">1 · Infrastructure Setup</div><h2>Project → site → system → asset</h2></div><span className="badge">{session?session.role:'Loading session'}</span></div>
   <div className="grid two" style={{marginTop:14}}>
    <form onSubmit={e=>submitForm(e,'/api/projects','Project')}><h3>New project</h3><div style={gridStyle}><input name="projectCode" placeholder="Project code" required style={inputStyle}/><input name="name" placeholder="Project name" required style={inputStyle}/><input name="clientName" placeholder="Client" style={inputStyle}/><input name="address" placeholder="Address" style={inputStyle}/></div><button className="action" style={{marginTop:10}} disabled={!!busy}>{busy==='Project'?'Creating…':'Create project'}</button></form>
    <form onSubmit={e=>submitForm(e,'/api/sites','Site')}><h3>New site</h3><div style={gridStyle}><select name="projectId" style={inputStyle} defaultValue=""><option value="">Project (optional)</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code} · {p.name}</option>)}</select><input name="name" placeholder="Site name" required style={inputStyle}/><input name="address" placeholder="Site address" style={inputStyle}/></div><button className="action" style={{marginTop:10}} disabled={!!busy}>{busy==='Site'?'Creating…':'Create site'}</button></form>
    <form onSubmit={e=>submitForm(e,'/api/systems','System')}><h3>New system</h3><div style={gridStyle}><select name="siteId" required style={inputStyle} defaultValue=""><option value="" disabled>Choose site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="name" placeholder="System name" required style={inputStyle}/><input name="systemType" placeholder="System type" style={inputStyle}/></div><button className="action" style={{marginTop:10}} disabled={!!busy}>{busy==='System'?'Creating…':'Create system'}</button></form>
    <form onSubmit={async e=>{e.preventDefault();setBusy('Asset');setMessage('');const f=new FormData(e.currentTarget);const body:any=Object.fromEntries(f.entries());body.specifications={};try{await json('/api/assets',{method:'POST',body:JSON.stringify(body)});setMessage('Asset registered.');e.currentTarget.reset();await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}}><h3>Register asset</h3><div style={gridStyle}><select name="projectId" required style={inputStyle} defaultValue=""><option value="" disabled>Project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code}</option>)}</select><select name="siteId" required style={inputStyle} defaultValue=""><option value="" disabled>Site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="systemId" style={inputStyle} defaultValue=""><option value="">System (optional)</option>{systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="assetCode" placeholder="Asset code" required style={inputStyle}/><input name="assetType" placeholder="Asset type" required style={inputStyle}/><input name="name" placeholder="Asset name" required style={inputStyle}/><input name="model" placeholder="Model" style={inputStyle}/><input name="serialNumber" placeholder="Serial number" style={inputStyle}/><input name="locationLabel" placeholder="Physical location" style={inputStyle}/></div><button className="action" style={{marginTop:10}} disabled={!!busy}>{busy==='Asset'?'Registering…':'Register asset'}</button></form>
   </div>
  </section>
  <section className="card"><div className="eyebrow">2 · Field Lifecycle</div><h2>Submit work and evidence</h2><div style={{...gridStyle,marginTop:12}}><select value={projectId} onChange={e=>{setProjectId(e.target.value);setSiteId('');setSystemId('');setAssetId('')}} style={inputStyle}><option value="">All projects</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code} · {p.name}</option>)}</select><select value={siteId} onChange={e=>{setSiteId(e.target.value);setSystemId('');setAssetId('')}} style={inputStyle}><option value="">All sites</option>{filteredSites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={systemId} onChange={e=>{setSystemId(e.target.value);setAssetId('')}} style={inputStyle}><option value="">All systems</option>{filteredSystems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={assetId} onChange={e=>{setAssetId(e.target.value);setEventId('')}} style={inputStyle}><option value="">Choose asset</option>{filteredAssets.map(a=><option key={a.id} value={a.id}>{a.asset_code} · {a.name}</option>)}</select><select value={eventType} onChange={e=>setEventType(e.target.value)} style={inputStyle}>{eventTypes.map(x=><option key={x}>{x}</option>)}</select><input value={eventNotes} onChange={e=>setEventNotes(e.target.value)} placeholder="Work notes / measurements / observations" style={inputStyle}/></div><div className="button-row"><button className="action" onClick={createLifecycle} disabled={!!busy}>{busy==='lifecycle'?'Submitting…':'Submit lifecycle event'}</button>{eventId&&<label className="ghost" style={{cursor:'pointer'}}>Add evidence<input type="file" hidden onChange={e=>uploadEvidence(e.target.files?.[0]||null)}/></label>}</div>{eventId&&<div className="muted" style={{marginTop:10}}>Current event: <span className="mono">{eventId}</span></div>}</section>
  <section className="card"><div className="section-head"><div><div className="eyebrow">3 · Independent Approval</div><h2>Pending verification queue</h2></div><span className="badge">{pending.length} pending</span></div><div className="timeline" style={{marginTop:12}}>{pending.map(x=><div className="event" key={x.id}><i className="event-icon">{x.evidence_count||0}</i><div style={{flex:1}}><strong>{x.event_type} · {x.asset_code} · {x.asset_name}</strong><small>{x.project_code} · Performed by {x.performer_name||x.performer_email||'Unknown'} · {x.evidence_count} evidence item(s)<br/><span className="mono">{x.payload_sha256}</span></small></div><button className={x.performed_by_me?'ghost':'action'} disabled={!!busy} onClick={()=>approve(x)}>{x.performed_by_me?'Performer — cannot approve':busy===x.id?'Anchoring…':'Approve & anchor'}</button></div>)}{!pending.length&&<div className="muted">No submitted lifecycle events are waiting for approval.</div>}</div></section>
 </div>
}