'use client';
import {useEffect,useMemo,useState} from 'react';

type Project={id:string;project_code:string;name:string;client_name?:string|null};
type Site={id:string;project_id?:string|null;name:string;project_name?:string|null};
type System={id:string;site_id:string;name:string;system_type?:string|null};
type Asset={id:string;project_id:string;site_id:string;system_id?:string|null;asset_code:string;name:string;serial_number?:string|null};
type Session={userId:string;email:string;role:string};
type WorkflowEvent={id:string;event_type:string;status:string;occurred_at:string;evidence_count:number;approval_count:number};
type WorkflowState={verified:string[];pending:string[];allowed:string[];blocked:Record<string,string>;recommendedNext:string|null;phase:string;terminal:boolean;inferredPrerequisites:string[];descriptions:Record<string,string>};
type WorkflowResponse={assetId:string;projectId:string;state:WorkflowState;events:WorkflowEvent[]};

const inputStyle={width:'100%',padding:'10px 11px',borderRadius:10,border:'1px solid #21405a',background:'#081723',color:'#eef6ff'} as const;
const gridStyle={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10} as const;
async function json<T=any>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,{...options,headers:{...(options?.body instanceof FormData?{}:{'content-type':'application/json'}),...(options?.headers||{})}});const x=await r.json();if(!r.ok)throw new Error(x.error||`Request failed (${r.status})`);return x}

export default function OperationsConsole(){
 const [projects,setProjects]=useState<Project[]>([]),[sites,setSites]=useState<Site[]>([]),[systems,setSystems]=useState<System[]>([]),[assets,setAssets]=useState<Asset[]>([]),[session,setSession]=useState<Session|null>(null);
 const [busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const [projectId,setProjectId]=useState(''),[siteId,setSiteId]=useState(''),[systemId,setSystemId]=useState(''),[assetId,setAssetId]=useState('');
 const [assetProjectId,setAssetProjectId]=useState(''),[assetSiteId,setAssetSiteId]=useState(''),[assetSystemId,setAssetSystemId]=useState('');
 const [eventType,setEventType]=useState(''),[eventNotes,setEventNotes]=useState(''),[eventId,setEventId]=useState(''),[workflow,setWorkflow]=useState<WorkflowResponse|null>(null);

 async function refresh(){const [p,si,sy,a,pe]=await Promise.all([json('/api/projects'),json('/api/sites'),json('/api/systems'),json('/api/assets'),json('/api/pending')]);setProjects(p.items||[]);setSites(si.items||[]);setSystems(sy.items||[]);setAssets(a.items||[]);setSession(pe.session||null)}
 async function loadWorkflow(id:string){if(!id){setWorkflow(null);setEventType('');setEventId('');return}const x=await json<WorkflowResponse>(`/api/lifecycle?assetId=${encodeURIComponent(id)}`);setWorkflow(x);setEventType(current=>x.state.allowed.includes(current)?current:(x.state.recommendedNext||x.state.allowed[0]||''));setEventId(current=>{if(current&&x.events.some(e=>e.id===current&&e.status==='SUBMITTED'))return current;const pending=[...x.events].reverse().find(e=>e.status==='SUBMITTED');return pending?.id||''})}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
 useEffect(()=>{loadWorkflow(assetId).catch(e=>setMessage(e.message))},[assetId]);

 const filteredSites=useMemo(()=>sites.filter(s=>!projectId||s.project_id===projectId),[sites,projectId]);
 const filteredSystems=useMemo(()=>systems.filter(s=>!siteId||s.site_id===siteId),[systems,siteId]);
 const filteredAssets=useMemo(()=>assets.filter(a=>(!projectId||a.project_id===projectId)&&(!siteId||a.site_id===siteId)&&(!systemId||a.system_id===systemId)),[assets,projectId,siteId,systemId]);
 const assetSites=useMemo(()=>sites.filter(s=>s.project_id===assetProjectId),[sites,assetProjectId]);
 const assetSystems=useMemo(()=>systems.filter(s=>s.site_id===assetSiteId),[systems,assetSiteId]);
 const pendingEvents=workflow?.events.filter(e=>e.status==='SUBMITTED')||[];
 const activeEvent=pendingEvents.find(e=>e.id===eventId);
 const canSetup=!!session&&['SUPER_ADMIN','ORG_ADMIN','PROJECT_MANAGER'].includes(session.role);

 async function submitForm(e:React.FormEvent<HTMLFormElement>,url:string,label:string){e.preventDefault();setBusy(label);setMessage('');const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries());for(const k of Object.keys(body))if(body[k]==='')delete body[k];try{await json(url,{method:'POST',body:JSON.stringify(body)});setMessage(`${label} created.`);e.currentTarget.reset();await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}

 async function createAsset(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy('Asset');setMessage('');const f=new FormData(e.currentTarget);const body:any=Object.fromEntries(f.entries());body.specifications={};try{const created=await json<Asset>('/api/assets',{method:'POST',body:JSON.stringify(body)});setMessage(`Asset record ${created.asset_code} created. Its first verified lifecycle event must be REGISTER_ASSET.`);e.currentTarget.reset();setAssetProjectId('');setAssetSiteId('');setAssetSystemId('');await refresh();setProjectId(created.project_id);setSiteId(created.site_id);setSystemId(created.system_id||'');setAssetId(created.id)}catch(err:any){setMessage(err.message)}finally{setBusy('')}}

 async function createLifecycle(){if(!assetId||!workflow)return setMessage('Select an asset first.');if(!eventType||!workflow.state.allowed.includes(eventType))return setMessage('Choose an allowed lifecycle event.');const asset=assets.find(a=>a.id===assetId);if(!asset)return;setBusy('lifecycle');setMessage('');try{const x=await json('/api/lifecycle',{method:'POST',body:JSON.stringify({projectId:asset.project_id,assetId,eventType,payload:{notes:eventNotes,assetCode:asset.asset_code,source:'STRATUM Verified Operational Workflow'}})});setEventId(x.id);setEventNotes('');setMessage(`${eventType} submitted. Attach supporting evidence, then an independent approver can finalize the record.`);await loadWorkflow(assetId);await refresh()}catch(err:any){setMessage(err.message);await loadWorkflow(assetId).catch(()=>{})}finally{setBusy('')}}

 async function uploadEvidence(files:FileList|null){if(!files?.length||!eventId||!assetId)return setMessage('Select a submitted lifecycle event and one or more files first.');setBusy('evidence');setMessage('');try{let count=0;for(const file of Array.from(files)){const bytes=await file.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');const fd=new FormData();fd.set('file',file);fd.set('lifecycleEventId',eventId);fd.set('assetId',assetId);fd.set('kind','FIELD_EVIDENCE');fd.set('visibility','PRIVATE');fd.set('sha256',digest);await json('/api/evidence/upload',{method:'POST',body:fd});count++}setMessage(`${count} evidence file${count===1?'':'s'} stored with server-verified SHA-256 fingerprints.`);await loadWorkflow(assetId);await refresh()}catch(err:any){setMessage(err.message)}finally{setBusy('')}}

 return <div className="grid" style={{gap:16}}>
  {message&&<div className="card notice"><strong>System</strong><span>{message}</span></div>}
  <section className="card"><div className="section-head"><div><div className="eyebrow">1 · Infrastructure Identity</div><h2>Project → site → system → asset</h2><p className="muted">Creating an asset record establishes database identity only. Cryptographic provenance starts with a separately approved REGISTER_ASSET lifecycle event.</p></div><span className="badge">{session?session.role.replaceAll('_',' '):'Loading session'}</span></div>
   {canSetup?<div className="grid two" style={{marginTop:14}}>
    <form onSubmit={e=>submitForm(e,'/api/projects','Project')}><h3>New project</h3><div style={gridStyle}><input name="projectCode" placeholder="Project code" required style={inputStyle}/><input name="name" placeholder="Project name" required style={inputStyle}/><input name="clientName" placeholder="Client" style={inputStyle}/><input name="address" placeholder="Address" style={inputStyle}/></div><button className="action" style={{marginTop:10}} disabled={!!busy}>{busy==='Project'?'Creating…':'Create project'}</button></form>
    <form onSubmit={e=>submitForm(e,'/api/sites','Site')}><h3>New site</h3><div style={gridStyle}><select name="projectId" style={inputStyle} defaultValue="" required><option value="" disabled>Choose project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code} · {p.name}</option>)}</select><input name="name" placeholder="Site name" required style={inputStyle}/><input name="address" placeholder="Site address" style={inputStyle}/></div><button className="action" style={{marginTop:10}} disabled={!!busy}>{busy==='Site'?'Creating…':'Create site'}</button></form>
    <form onSubmit={e=>submitForm(e,'/api/systems','System')}><h3>New system</h3><div style={gridStyle}><select name="siteId" required style={inputStyle} defaultValue=""><option value="" disabled>Choose site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.project_name?`${s.project_name} · `:''}{s.name}</option>)}</select><input name="name" placeholder="System name" required style={inputStyle}/><input name="systemType" placeholder="System type" style={inputStyle}/></div><button className="action" style={{marginTop:10}} disabled={!!busy}>{busy==='System'?'Creating…':'Create system'}</button></form>
    <form onSubmit={createAsset}><h3>Create asset record</h3><div style={gridStyle}><select name="projectId" required style={inputStyle} value={assetProjectId} onChange={e=>{setAssetProjectId(e.target.value);setAssetSiteId('');setAssetSystemId('')}}><option value="" disabled>Project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code} · {p.name}</option>)}</select><select name="siteId" required style={inputStyle} value={assetSiteId} disabled={!assetProjectId} onChange={e=>{setAssetSiteId(e.target.value);setAssetSystemId('')}}><option value="" disabled>Site</option>{assetSites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="systemId" style={inputStyle} value={assetSystemId} disabled={!assetSiteId} onChange={e=>setAssetSystemId(e.target.value)}><option value="">System (optional)</option>{assetSystems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="assetCode" placeholder="Asset code" required style={inputStyle}/><input name="assetType" placeholder="Asset type" required style={inputStyle}/><input name="name" placeholder="Asset name" required style={inputStyle}/><input name="model" placeholder="Model" style={inputStyle}/><input name="serialNumber" placeholder="Serial number" style={inputStyle}/><input name="locationLabel" placeholder="Physical location" style={inputStyle}/></div><button className="action" style={{marginTop:10}} disabled={!!busy}>{busy==='Asset'?'Creating…':'Create asset record'}</button></form>
   </div>:<div className="notice" style={{marginTop:14}}><strong>Field role</strong><span>Your role can perform lifecycle work on assigned projects. Project/site/system/asset master-data creation is limited to project managers and administrators.</span></div>}
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">2 · Controlled Field Lifecycle</div><h2>Perform the next valid step</h2><p className="muted">Only lifecycle events whose verified prerequisites are satisfied are offered for submission.</p></div>{workflow&&<span className="badge">{workflow.state.phase.replaceAll('_',' ')}</span>}</div>
   <div style={{...gridStyle,marginTop:12}}><select value={projectId} onChange={e=>{setProjectId(e.target.value);setSiteId('');setSystemId('');setAssetId('')}} style={inputStyle}><option value="">All projects</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code} · {p.name}</option>)}</select><select value={siteId} onChange={e=>{setSiteId(e.target.value);setSystemId('');setAssetId('')}} style={inputStyle}><option value="">All sites</option>{filteredSites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={systemId} onChange={e=>{setSystemId(e.target.value);setAssetId('')}} style={inputStyle}><option value="">All systems</option>{filteredSystems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={assetId} onChange={e=>setAssetId(e.target.value)} style={inputStyle}><option value="">Choose asset</option>{filteredAssets.map(a=><option key={a.id} value={a.id}>{a.asset_code} · {a.name}</option>)}</select></div>
   {workflow&&<><div className="grid two" style={{marginTop:14}}><div><div className="label">Verified milestones</div><div className="button-row">{workflow.state.verified.length?workflow.state.verified.map(x=><span className="proof" key={x}>✓ {x}</span>):<span className="muted">No verified lifecycle event yet</span>}</div></div><div><div className="label">Awaiting approval</div><div className="button-row">{workflow.state.pending.length?workflow.state.pending.map(x=><span className="pending" key={x}>{x}</span>):<span className="muted">Nothing pending</span>}</div></div></div>{workflow.state.inferredPrerequisites.length>0&&<div className="notice" style={{marginTop:12}}><strong>Legacy continuity</strong><span>Older downstream records imply transition prerequisites for workflow continuity, but only explicitly verified milestones are shown as proof: {workflow.state.inferredPrerequisites.join(', ')}.</span></div>}
   {!workflow.state.terminal?<><div style={{...gridStyle,marginTop:14}}><select value={eventType} onChange={e=>setEventType(e.target.value)} style={inputStyle} disabled={!workflow.state.allowed.length}><option value="" disabled>Choose allowed event</option>{workflow.state.allowed.map(x=><option key={x} value={x}>{x}{x===workflow.state.recommendedNext?' · recommended':''}</option>)}</select><input value={eventNotes} onChange={e=>setEventNotes(e.target.value)} placeholder="Work notes, measurements, observations or reference" style={inputStyle}/></div>{eventType&&<p className="muted" style={{marginTop:8}}>{workflow.state.descriptions[eventType]}</p>}<div className="button-row"><button className="action" onClick={createLifecycle} disabled={!!busy||!eventType}>{busy==='lifecycle'?'Submitting…':`Submit ${eventType||'lifecycle event'}`}</button></div></>:<div className="notice" style={{marginTop:14}}><strong>Lifecycle closed</strong><span>This asset has a verified DECOMMISSION event. No further operational lifecycle events are allowed.</span></div>}</>}
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">3 · Evidence Package</div><h2>Attach evidence to submitted work</h2><p className="muted">You can leave and return later. Submitted events remain selectable until approved or rejected.</p></div><span className="badge">{pendingEvents.length} pending</span></div>{pendingEvents.length?<><select value={eventId} onChange={e=>setEventId(e.target.value)} style={{...inputStyle,marginTop:12}}>{pendingEvents.map(e=><option key={e.id} value={e.id}>{e.event_type} · {e.evidence_count} evidence · {e.approval_count} approval(s)</option>)}</select>{activeEvent&&<div className="button-row"><label className="action" style={{cursor:'pointer'}}>{busy==='evidence'?'Hashing & storing…':'Add evidence files'}<input type="file" multiple hidden disabled={!!busy} onChange={e=>{uploadEvidence(e.target.files);e.currentTarget.value=''}}/></label><span className="muted">Current package: {activeEvent.evidence_count} file(s)</span></div>}</>:<p className="muted" style={{marginTop:12}}>No submitted lifecycle event is waiting for evidence. Create a valid lifecycle event above first.</p>}</section>
 </div>
}
