'use client';
import {useMemo,useState} from 'react';

type Asset={id:string;projectId:string;projectCode:string;assetCode:string;name:string;assetType:string};
type Project={id:string;projectCode:string;name:string};
type ImpactItem={asset_id:string;asset_code:string;name:string;asset_type:string;relationship_type:string;criticality:string;depth:number;project_code:string;project_name:string};
type Impact={schemaReady:boolean;root:null|{asset_code:string;name:string;asset_type:string;project_code:string;project_name:string};items:ImpactItem[]};
const input={width:'100%',padding:'10px 11px',borderRadius:10,border:'1px solid #21405a',background:'#081723',color:'#eef6ff'} as const;
const grid={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10} as const;
async function json(url:string,options?:RequestInit){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options?.headers||{})}});const x=await r.json();if(!r.ok)throw new Error(x.error||`Request failed (${r.status})`);return x}
function split(v:string){return v.split(',').map(x=>x.trim()).filter(Boolean)}
function parseValue(v:string){const t=v.trim();if(t==='true')return true;if(t==='false')return false;if(t==='null')return null;const n=Number(t);if(t!==''&&Number.isFinite(n))return n;try{return JSON.parse(t)}catch{return t}}

export default function OperationalIntelligenceConsole({schemaReady,projects,assets}:{schemaReady:boolean;projects:Project[];assets:Asset[]}){
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(''),[projectId,setProjectId]=useState(projects[0]?.id||'');
 const [impactAsset,setImpactAsset]=useState(''),[direction,setDirection]=useState<'DOWNSTREAM'|'UPSTREAM'>('DOWNSTREAM'),[impact,setImpact]=useState<Impact|null>(null);
 const projectAssets=useMemo(()=>assets.filter(a=>!projectId||a.projectId===projectId),[assets,projectId]);
 async function post(body:any,label:string){if(!schemaReady){setMessage('Operational Intelligence migration 007 must be applied before records can be created.');return}setBusy(label);setMessage('');try{await json('/api/operational-intelligence',{method:'POST',body:JSON.stringify(body)});setMessage(`${label} saved.`);window.location.reload()}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 async function analyze(){if(!impactAsset)return setMessage('Choose an asset to analyze.');setBusy('impact');setMessage('');try{setImpact(await json(`/api/operational-intelligence?view=impact&assetId=${encodeURIComponent(impactAsset)}&direction=${direction}`))}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 return <div className="grid" style={{gap:16}}>
  {message&&<div className="card notice"><strong>STRATUM</strong><span>{message}</span></div>}
  {!schemaReady&&<div className="card notice"><strong>Database activation pending</strong><span>The feature code is installed, but migration 007 must be applied to the production database before operational records can be written. Existing STRATUM Verified functionality is unaffected.</span></div>}
  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Impact Analysis</div><h2>Trace infrastructure consequences</h2><p className="muted">Walk the verified operational topology upstream or downstream from any STRATUM Asset.</p></div><span className="badge">GRAPH TRACE</span></div>
   <div style={{...grid,marginTop:12}}><select value={impactAsset} onChange={e=>setImpactAsset(e.target.value)} style={input}><option value="">Choose STRATUM Asset</option>{assets.map(a=><option value={a.id} key={a.id}>{a.projectCode} · {a.assetCode} · {a.name}</option>)}</select><select value={direction} onChange={e=>setDirection(e.target.value as any)} style={input}><option value="DOWNSTREAM">Downstream impact</option><option value="UPSTREAM">Upstream dependencies</option></select></div><div className="button-row"><button className="action" disabled={busy==='impact'} onClick={analyze}>{busy==='impact'?'Tracing…':'Run impact analysis'}</button></div>
   {impact?.root&&<div style={{marginTop:14}}><div className="notice"><strong>{impact.root.asset_code} · {impact.root.name}</strong><span>{direction==='DOWNSTREAM'?'Affected downstream infrastructure':'Required upstream infrastructure'} · {impact.items.length} linked asset(s)</span></div><div className="grid two" style={{marginTop:10}}>{impact.items.map(x=><div className="stat" key={`${x.asset_id}-${x.depth}`}><span>Depth {x.depth} · {x.relationship_type}</span><strong>{x.asset_code}</strong><small>{x.name} · {x.asset_type} · {x.criticality}</small></div>)}</div>{!impact.items.length&&<p className="muted">No operational dependency edges have been recorded for this direction yet.</p>}</div>}
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Human Touchpoints</div><h2>Register where humans can change infrastructure state</h2></div><span className="badge">L7 OPERATIONS</span></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({kind:'touchpoint',projectId:f.get('projectId'),assetId:f.get('assetId'),touchpointCode:f.get('code'),name:f.get('name'),touchpointType:f.get('type'),currentState:f.get('state')||undefined,permittedActions:split(String(f.get('actions')||'')),restrictedActions:split(String(f.get('restricted')||'')),requiredRole:f.get('role')||undefined,authorizationLevel:f.get('auth')||undefined,lotoRequired:f.get('loto')==='on',hazards:split(String(f.get('hazards')||'')),interlocks:split(String(f.get('interlocks')||''))},'Human Touchpoint')}}>
    <div style={{...grid,marginTop:12}}><select name="projectId" value={projectId} onChange={e=>setProjectId(e.target.value)} style={input} required>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="assetId" style={input} required><option value="">Asset</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><input name="code" placeholder="Touchpoint code · HTP-SWGR01-CB04" style={input} required/><input name="name" placeholder="Name · CB-04 breaker handle" style={input} required/><input name="type" placeholder="Type · BREAKER_HANDLE / HMI / VALVE" style={input} required/><input name="state" placeholder="Current state · CLOSED" style={input}/><input name="actions" placeholder="Permitted actions · OPEN, CLOSE" style={input}/><input name="restricted" placeholder="Restricted actions" style={input}/><input name="role" placeholder="Required role" style={input}/><input name="auth" placeholder="Authorization level" style={input}/><input name="hazards" placeholder="Hazards · Arc Flash, Shock" style={input}/><input name="interlocks" placeholder="Interlocks · KIRK-01, 86 Lockout" style={input}/></div><label className="muted" style={{display:'flex',gap:8,alignItems:'center',marginTop:10}}><input name="loto" type="checkbox"/> LOTO required</label><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Human Touchpoint'?'Saving…':'Register Human Touchpoint'}</button></div>
   </form>
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Procedure Intelligence</div><h2>Create machine-readable SOP / MOP / EOP records</h2></div><span className="badge">PROCEDURE GRAPH</span></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({kind:'procedure',projectId:f.get('projectId'),procedureCode:f.get('code'),procedureType:f.get('type'),title:f.get('title'),purpose:f.get('purpose')||undefined,version:f.get('version')||'1.0',status:f.get('status')||'DRAFT',sourceRefs:[]},'Procedure')}}><div style={{...grid,marginTop:12}}><select name="projectId" style={input} required>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="type" style={input} defaultValue="SOP"><option>SOP</option><option>MOP</option><option>EOP</option><option>MAINTENANCE</option><option>LOTO</option><option>COMMISSIONING</option></select><input name="code" placeholder="Procedure code · MOP-ELEC-042" style={input} required/><input name="title" placeholder="Procedure title" style={input} required/><input name="version" defaultValue="1.0" placeholder="Version" style={input}/><select name="status" style={input} defaultValue="DRAFT"><option>DRAFT</option><option>REVIEW</option><option>APPROVED</option></select><input name="purpose" placeholder="Purpose / operating objective" style={{...input,gridColumn:'1 / -1'}}/></div><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Procedure'?'Saving…':'Create Procedure'}</button></div></form>
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Topology</div><h2>Connect STRATUM Assets operationally</h2><p className="muted">These edges power upstream/downstream impact analysis and later procedure simulation.</p></div></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({kind:'dependency',projectId:f.get('projectId'),sourceAssetId:f.get('source'),targetAssetId:f.get('target'),relationshipType:f.get('relationship'),criticality:f.get('criticality'),sourceRef:{}},'Topology relationship')}}><div style={{...grid,marginTop:12}}><select name="projectId" value={projectId} onChange={e=>setProjectId(e.target.value)} style={input}>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="relationship" style={input} defaultValue="FEEDS"><option>FEEDS</option><option>COOLS</option><option>CONTROLS</option><option>DEPENDS_ON</option><option>PROTECTS</option><option>BYPASSES</option><option>REDUNDANT_TO</option><option>CONNECTED_TO</option></select><select name="source" style={input} required><option value="">Source asset</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><select name="target" style={input} required><option value="">Target asset</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><select name="criticality" style={input} defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Topology relationship'?'Saving…':'Add topology relationship'}</button></div></form>
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Live Iterations</div><h2>Capture near-real-time observed state</h2><p className="muted">State Iterations update operational truth without rewriting the engineering baseline.</p></div><span className="badge">STATE ITERATION</span></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({kind:'observation',projectId:f.get('projectId'),assetId:f.get('assetId'),sourceSystem:f.get('sourceSystem'),pointKey:f.get('pointKey'),value:parseValue(String(f.get('value')||'')),quality:f.get('quality'),observedAt:new Date().toISOString()},'Live Observation')}}><div style={{...grid,marginTop:12}}><select name="projectId" value={projectId} onChange={e=>setProjectId(e.target.value)} style={input}>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="assetId" style={input} required><option value="">Asset</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><input name="sourceSystem" placeholder="Source · EPMS / BMS / PLC / DCIM" style={input} required/><input name="pointKey" placeholder="Point · breaker_state / load_pct" style={input} required/><input name="value" placeholder="Value · CLOSED / 73.2 / true" style={input} required/><select name="quality" style={input} defaultValue="GOOD"><option>GOOD</option><option>UNCERTAIN</option><option>BAD</option><option>STALE</option></select></div><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Live Observation'?'Saving…':'Record State Iteration'}</button></div></form>
  </section>
 </div>
}
