'use client';
import {useEffect,useMemo,useState} from 'react';

type Asset={id:string;projectId:string;projectCode:string;assetCode:string;name:string;assetType:string};
type Project={id:string;projectCode:string;name:string};
type Procedure={id:string;projectId:string;procedureCode:string;procedureType:string;title:string;version:string;status:string;stepCount:number};
type Touchpoint={id:string;projectId:string;assetId:string;touchpointCode:string;name:string};
type Run={id:string;projectId:string;procedureId:string;procedureCode:string;procedureType:string;procedureTitle:string;status:string;currentStepCode?:string|null;currentStepTitle?:string|null;currentInstruction?:string|null;currentExpectedState?:Record<string,unknown>|null;currentPrerequisites?:Record<string,unknown>|null;currentIsBlocking?:boolean|null;currentFailureBranch?:string|null;verifiedSteps:number;totalSteps:number;createdAt:string};
type ImpactItem={asset_id:string;asset_code:string;name:string;asset_type:string;relationship_type:string;criticality:string;depth:number;project_code:string;project_name:string};
type Impact={schemaReady:boolean;root:null|{asset_code:string;name:string;asset_type:string;project_code:string;project_name:string};items:ImpactItem[]};
type SimulationStep={procedure_step_id?:string;step_code:string;sequence_no:number;title:string;instruction:string;is_blocking:boolean;readiness:'PASS'|'WARNING'|'BLOCK';prerequisiteResults:Array<{status:string;reason:string}>;currentExpectedPointCheck:{status:string;reason:string;observed?:unknown}};
type Simulation={procedure:null|{procedure_code:string;procedure_type:string;title:string;version:string;status:string};summary:{pass:number;warning:number;block:number};steps:SimulationStep[]};
type RunDetail={id:string;project_id:string;procedure_id:string;execution_mode:string;status:string;current_step_id:string|null;procedure_code:string;procedure_type:string;procedure_title:string;version:string;steps:Array<{procedure_step_id:string;sequence_no:number;step_code:string;title:string;instruction:string;actor_role?:string|null;asset_code?:string|null;asset_name?:string|null;touchpoint_code?:string|null;touchpoint_name?:string|null;prerequisites:Record<string,unknown>;expected_state:Record<string,unknown>;failure_branch_step_code?:string|null;is_blocking:boolean;step_run_status?:string|null;verification_result?:Record<string,unknown>|null;operator_note?:string|null}>};
const input={width:'100%',padding:'10px 11px',borderRadius:10,border:'1px solid #21405a',background:'#081723',color:'#eef6ff'} as const;
const grid={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10} as const;
async function json(url:string,options?:RequestInit){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options?.headers||{})}});const x=await r.json();if(!r.ok)throw new Error(x.error||`Request failed (${r.status})`);return x}
function split(v:string){return v.split(',').map(x=>x.trim()).filter(Boolean)}
function parseValue(v:string){const t=v.trim();if(t==='true')return true;if(t==='false')return false;if(t==='null')return null;const n=Number(t);if(t!==''&&Number.isFinite(n))return n;try{return JSON.parse(t)}catch{return t}}
function parseObject(v:string,label:string){const t=v.trim();if(!t)return{};const x=JSON.parse(t);if(!x||Array.isArray(x)||typeof x!=='object')throw new Error(`${label} must be a JSON object.`);return x}
function compact(x:unknown){try{return JSON.stringify(x)}catch{return String(x)}}

export default function OperationalIntelligenceConsole({schemaReady,executionReady,projects,assets,procedures,touchpoints,runs}:{schemaReady:boolean;executionReady:boolean;projects:Project[];assets:Asset[];procedures:Procedure[];touchpoints:Touchpoint[];runs:Run[]}){
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(''),[projectId,setProjectId]=useState(projects[0]?.id||'');
 const [impactAsset,setImpactAsset]=useState(''),[direction,setDirection]=useState<'DOWNSTREAM'|'UPSTREAM'>('DOWNSTREAM'),[impact,setImpact]=useState<Impact|null>(null);
 const [builderProcedureId,setBuilderProcedureId]=useState(''),[executionProcedureId,setExecutionProcedureId]=useState(''),[simulation,setSimulation]=useState<Simulation|null>(null);
 const [selectedRunId,setSelectedRunId]=useState(runs.find(r=>['RUNNING','BLOCKED','READY'].includes(r.status))?.id||runs[0]?.id||''),[runDetail,setRunDetail]=useState<RunDetail|null>(null),[manualConfirmed,setManualConfirmed]=useState(false),[operatorNote,setOperatorNote]=useState('');
 const projectAssets=useMemo(()=>assets.filter(a=>!projectId||a.projectId===projectId),[assets,projectId]);
 const projectProcedures=useMemo(()=>procedures.filter(p=>!projectId||p.projectId===projectId),[procedures,projectId]);
 const approvedProcedures=useMemo(()=>procedures.filter(p=>p.status==='APPROVED'&&p.stepCount>0),[procedures]);
 const projectTouchpoints=useMemo(()=>touchpoints.filter(t=>!projectId||t.projectId===projectId),[touchpoints,projectId]);
 const currentStep=useMemo(()=>runDetail?.steps.find(s=>s.procedure_step_id===runDetail.current_step_id)||null,[runDetail]);
 async function post(body:any,label:string){if(!schemaReady){setMessage('Operational Intelligence migration 007 must be active before records can be created.');return}setBusy(label);setMessage('');try{await json('/api/operational-intelligence',{method:'POST',body:JSON.stringify(body)});setMessage(`${label} saved.`);window.location.reload()}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 async function analyze(){if(!impactAsset)return setMessage('Choose an asset to analyze.');setBusy('impact');setMessage('');try{setImpact(await json(`/api/operational-intelligence?view=impact&assetId=${encodeURIComponent(impactAsset)}&direction=${direction}`))}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 async function loadRun(id:string){if(!id||!executionReady){setRunDetail(null);return}try{setRunDetail(await json(`/api/procedure-execution?view=run&runId=${encodeURIComponent(id)}`))}catch(e:any){setMessage(e.message);setRunDetail(null)}}
 useEffect(()=>{loadRun(selectedRunId)},[selectedRunId,executionReady]);
 async function simulate(){if(!executionProcedureId)return setMessage('Choose an approved procedure first.');setBusy('simulate');setMessage('');try{setSimulation(await json(`/api/procedure-execution?view=simulation&procedureId=${encodeURIComponent(executionProcedureId)}`))}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 async function exec(body:any,label:string){if(!executionReady)return setMessage('Procedure Execution migration 008 must be active before live runs can start.');setBusy(label);setMessage('');try{const x=await json('/api/procedure-execution',{method:'POST',body:JSON.stringify(body)});setMessage(`${label}: ${x.status||'complete'}.`);setManualConfirmed(false);setOperatorNote('');window.location.reload()}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 return <div className="grid" style={{gap:16}}>
  {message&&<div className="card notice"><strong>STRATUM</strong><span>{message}</span></div>}
  {!schemaReady&&<div className="card notice"><strong>Operational graph unavailable</strong><span>Migration 007 is not active. Existing STRATUM Verified lifecycle and DIR functionality remains unaffected.</span></div>}
  {!executionReady&&<div className="card notice"><strong>Procedure Execution activation pending</strong><span>The v2 execution engine is installed in this build but migration 008 must be promoted before live procedure runs can be stored. Procedure authoring and v1 Operational Intelligence remain available.</span></div>}

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Procedure Builder</div><h2>Turn SOP / MOP / EOP documents into executable steps</h2><p className="muted">Each step can bind an Asset, Human Touchpoint, machine-checkable prerequisites, an expected post-action state, and a failure branch.</p></div><span className="badge">HUMAN-IN-THE-LOOP</span></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{post({kind:'step',projectId:f.get('projectId'),procedureId:f.get('procedureId'),sequenceNo:Number(f.get('sequenceNo')),stepCode:f.get('stepCode'),title:f.get('title'),instruction:f.get('instruction'),actorRole:f.get('actorRole')||undefined,assetId:f.get('assetId')||undefined,touchpointId:f.get('touchpointId')||undefined,prerequisites:parseObject(String(f.get('prerequisites')||''),'Prerequisites'),expectedState:parseObject(String(f.get('expectedState')||''),'Expected state'),verification:parseObject(String(f.get('verification')||''),'Verification'),failureBranchStepCode:f.get('failureBranch')||undefined,isBlocking:f.get('blocking')==='on',sourceRef:{}},'Procedure Step')}catch(err:any){setMessage(err.message)}}}>
    <div style={{...grid,marginTop:12}}><select name="projectId" value={projectId} onChange={e=>{setProjectId(e.target.value);setBuilderProcedureId('')}} style={input} required>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="procedureId" value={builderProcedureId} onChange={e=>setBuilderProcedureId(e.target.value)} style={input} required><option value="">Procedure</option>{projectProcedures.map(p=><option value={p.id} key={p.id}>{p.procedureCode} · {p.procedureType} · {p.title}</option>)}</select><input name="sequenceNo" type="number" min="1" placeholder="Sequence number · 10" style={input} required/><input name="stepCode" placeholder="Step code · STEP-010" style={input} required/><input name="title" placeholder="Step title · Open CB-04" style={input} required/><input name="actorRole" placeholder="Actor role · Qualified Electrical Worker" style={input}/><select name="assetId" style={input}><option value="">STRATUM Asset (optional)</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><select name="touchpointId" style={input}><option value="">Human Touchpoint (optional)</option>{projectTouchpoints.map(t=><option value={t.id} key={t.id}>{t.touchpointCode} · {t.name}</option>)}</select><textarea name="instruction" placeholder="Operator instruction" style={{...input,gridColumn:'1 / -1',minHeight:80}} required/><textarea name="prerequisites" placeholder={'Prerequisites JSON · {"pointKey":"upstream_available","equals":true,"qualityIn":["GOOD"],"maxAgeSeconds":60}'} style={{...input,minHeight:94}}/><textarea name="expectedState" placeholder={'Expected state JSON · {"pointKey":"breaker_state","equals":"OPEN","qualityIn":["GOOD"],"maxAgeSeconds":30}'} style={{...input,minHeight:94}}/><textarea name="verification" placeholder={'Verification metadata JSON · {"method":"EPMS + visual"}'} style={{...input,minHeight:80}}/><input name="failureBranch" placeholder="Failure branch step code · EOP-010" style={input}/></div><label className="muted" style={{display:'flex',gap:8,alignItems:'center',marginTop:10}}><input name="blocking" type="checkbox" defaultChecked/> Block procedure when prerequisites or expected state fail</label><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Procedure Step'?'Saving…':'Add Procedure Step'}</button></div>
   </form>
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Procedure Simulation</div><h2>Dry-run readiness before field execution</h2><p className="muted">Simulation reads current STRATUM Live Iterations and checks blocking prerequisites. It never sends a control command and does not alter Verified engineering truth.</p></div><span className="badge">PASS · WARNING · BLOCK</span></div>
   <div style={{...grid,marginTop:12}}><select value={executionProcedureId} onChange={e=>{setExecutionProcedureId(e.target.value);setSimulation(null)}} style={input}><option value="">Choose approved procedure</option>{approvedProcedures.map(p=><option key={p.id} value={p.id}>{p.procedureCode} · {p.procedureType} · {p.title}</option>)}</select><div className="button-row" style={{margin:0}}><button type="button" className="action secondary" onClick={simulate} disabled={busy==='simulate'||!executionProcedureId}>{busy==='simulate'?'Simulating…':'Run Procedure Simulation'}</button><button type="button" className="action" onClick={()=>exec({action:'START',procedureId:executionProcedureId},'Start live procedure')} disabled={!executionReady||!executionProcedureId||!!busy}>Start Live Procedure</button></div></div>
   {simulation?.procedure&&<div style={{marginTop:14}}><div className="notice"><strong>{simulation.procedure.procedure_code} · {simulation.procedure.title}</strong><span>{simulation.summary.pass} pass · {simulation.summary.warning} warning · {simulation.summary.block} block</span></div>{simulation.steps.map(s=><div className="notice" key={s.step_code} style={{marginTop:8}}><strong>{s.sequence_no} · {s.step_code} · {s.readiness}</strong><span>{s.title} · Prerequisites: {s.prerequisiteResults.map(x=>`${x.status}: ${x.reason}`).join(' | ')} · Expected-state sensor check: {s.currentExpectedPointCheck.status}: {s.currentExpectedPointCheck.reason}</span></div>)}</div>}
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Procedure Execution</div><h2>Controlled step-by-step field execution</h2><p className="muted">Only APPROVED procedures can run. STRATUM verifies the expected state from Live Iterations where a machine rule exists; otherwise the step requires explicit human confirmation.</p></div><span className="badge">NO AUTONOMOUS ACTUATION</span></div>
   <select value={selectedRunId} onChange={e=>setSelectedRunId(e.target.value)} style={{...input,marginTop:12}}><option value="">Choose procedure run</option>{runs.map(r=><option key={r.id} value={r.id}>{r.procedureCode} · {r.status} · {r.verifiedSteps}/{r.totalSteps} verified</option>)}</select>
   {runDetail&&<div style={{marginTop:14}}><div className="grid four"><div className="stat"><span>Procedure</span><strong>{runDetail.procedure_code}</strong><small>{runDetail.procedure_type} · v{runDetail.version}</small></div><div className="stat"><span>Run status</span><strong>{runDetail.status}</strong><small>{runDetail.execution_mode}</small></div><div className="stat"><span>Verified steps</span><strong>{runDetail.steps.filter(s=>s.step_run_status==='VERIFIED').length}/{runDetail.steps.length}</strong><small>Execution evidence</small></div><div className="stat"><span>Current step</span><strong>{currentStep?.step_code||'—'}</strong><small>{currentStep?.title||'No active step'}</small></div></div>
    {currentStep&&<div className="notice" style={{marginTop:12}}><strong>{currentStep.sequence_no} · {currentStep.step_code} · {currentStep.title}</strong><span>{currentStep.instruction}{currentStep.touchpoint_code?` · Human Touchpoint ${currentStep.touchpoint_code}`:''}{currentStep.asset_code?` · Asset ${currentStep.asset_code}`:''}</span></div>}
    {currentStep&&<div className="grid two" style={{marginTop:10}}><div className="stat"><span>Prerequisites</span><strong>{compact(currentStep.prerequisites)}</strong><small>{currentStep.is_blocking?'Blocking':'Non-blocking'}</small></div><div className="stat"><span>Expected post-action state</span><strong>{compact(currentStep.expected_state)}</strong><small>Checked against latest Live Iteration when machine-verifiable</small></div></div>}
    {runDetail.status==='RUNNING'&&currentStep&&<><div style={{...grid,marginTop:12}}><input value={operatorNote} onChange={e=>setOperatorNote(e.target.value)} placeholder="Operator note / field observation" style={input}/><label className="muted" style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={manualConfirmed} onChange={e=>setManualConfirmed(e.target.checked)}/> Manual confirmation when no machine-verifiable expected-state rule exists</label></div><div className="button-row"><button className="action" disabled={!!busy} onClick={()=>exec({action:'VERIFY_STEP',runId:runDetail.id,manualConfirmed,note:operatorNote||undefined},'Verify current step')}>Action performed — Verify Expected vs Actual</button><button className="action secondary" disabled={!!busy} onClick={()=>exec({action:'ABORT',runId:runDetail.id,reason:operatorNote||'Operator aborted procedure'},'Abort procedure')}>Abort Procedure</button></div></>}
    {runDetail.status==='BLOCKED'&&<div className="notice" style={{marginTop:12}}><strong>STOP · Procedure blocked</strong><span>STRATUM detected an unsatisfied prerequisite or expected-vs-actual mismatch. Review the open exception and failure/recovery step before continuing.</span><div className="button-row"><button className="action" disabled={!!busy} onClick={()=>exec({action:'RESUME',runId:runDetail.id},'Resume failure/recovery branch')}>Re-check & Resume Failure/Recovery Branch</button><button className="action secondary" disabled={!!busy} onClick={()=>exec({action:'ABORT',runId:runDetail.id,reason:'Blocked procedure aborted by operator'},'Abort procedure')}>Abort Procedure</button></div></div>}
    <div className="card table-card" style={{marginTop:12}}><table className="table"><thead><tr><th>Step</th><th>Asset / Touchpoint</th><th>Execution</th><th>Verification</th></tr></thead><tbody>{runDetail.steps.map(s=><tr key={s.procedure_step_id}><td><strong>{s.sequence_no} · {s.step_code}</strong><div className="muted">{s.title}</div></td><td>{s.asset_code||'—'}<div className="muted">{s.touchpoint_code||'No touchpoint'}</div></td><td><span className={s.step_run_status==='VERIFIED'?'proof':s.step_run_status==='BLOCKED'||s.step_run_status==='FAILED'?'pending':'status-chip'}>{s.step_run_status||'PENDING'}</span></td><td><span className="muted">{s.verification_result?compact(s.verification_result):'—'}</span></td></tr>)}</tbody></table></div>
   </div>}
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Impact Analysis</div><h2>Trace infrastructure consequences</h2><p className="muted">Walk the operational topology upstream or downstream from any STRATUM Asset.</p></div><span className="badge">GRAPH TRACE</span></div>
   <div style={{...grid,marginTop:12}}><select value={impactAsset} onChange={e=>setImpactAsset(e.target.value)} style={input}><option value="">Choose STRATUM Asset</option>{assets.map(a=><option value={a.id} key={a.id}>{a.projectCode} · {a.assetCode} · {a.name}</option>)}</select><select value={direction} onChange={e=>setDirection(e.target.value as any)} style={input}><option value="DOWNSTREAM">Downstream impact</option><option value="UPSTREAM">Upstream dependencies</option></select></div><div className="button-row"><button className="action" disabled={busy==='impact'} onClick={analyze}>{busy==='impact'?'Tracing…':'Run impact analysis'}</button></div>
   {impact?.root&&<div style={{marginTop:14}}><div className="notice"><strong>{impact.root.asset_code} · {impact.root.name}</strong><span>{direction==='DOWNSTREAM'?'Affected downstream infrastructure':'Required upstream infrastructure'} · {impact.items.length} linked asset(s)</span></div><div className="grid two" style={{marginTop:10}}>{impact.items.map(x=><div className="stat" key={`${x.asset_id}-${x.depth}`}><span>Depth {x.depth} · {x.relationship_type}</span><strong>{x.asset_code}</strong><small>{x.name} · {x.asset_type} · {x.criticality}</small></div>)}</div>{!impact.items.length&&<p className="muted">No operational dependency edges have been recorded for this direction yet.</p>}</div>}
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Human Touchpoints</div><h2>Register where humans can change infrastructure state</h2></div><span className="badge">L7 OPERATIONS</span></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({kind:'touchpoint',projectId:f.get('projectId'),assetId:f.get('assetId'),touchpointCode:f.get('code'),name:f.get('name'),touchpointType:f.get('type'),currentState:f.get('state')||undefined,permittedActions:split(String(f.get('actions')||'')),restrictedActions:split(String(f.get('restricted')||'')),requiredRole:f.get('role')||undefined,authorizationLevel:f.get('auth')||undefined,lotoRequired:f.get('loto')==='on',hazards:split(String(f.get('hazards')||'')),interlocks:split(String(f.get('interlocks')||''))},'Human Touchpoint')}}>
    <div style={{...grid,marginTop:12}}><select name="projectId" value={projectId} onChange={e=>setProjectId(e.target.value)} style={input} required>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="assetId" style={input} required><option value="">Asset</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><input name="code" placeholder="Touchpoint code · HTP-SWGR01-CB04" style={input} required/><input name="name" placeholder="Name · CB-04 breaker handle" style={input} required/><input name="type" placeholder="Type · BREAKER_HANDLE / HMI / VALVE" style={input} required/><input name="state" placeholder="Current state · CLOSED" style={input}/><input name="actions" placeholder="Permitted actions · OPEN, CLOSE" style={input}/><input name="restricted" placeholder="Restricted actions" style={input}/><input name="role" placeholder="Required role" style={input}/><input name="auth" placeholder="Authorization level" style={input}/><input name="hazards" placeholder="Hazards · Arc Flash, Shock" style={input}/><input name="interlocks" placeholder="Interlocks · KIRK-01, 86 Lockout" style={input}/></div><label className="muted" style={{display:'flex',gap:8,alignItems:'center',marginTop:10}}><input name="loto" type="checkbox"/> LOTO required</label><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Human Touchpoint'?'Saving…':'Register Human Touchpoint'}</button></div>
   </form>
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Procedure Intelligence</div><h2>Create machine-readable SOP / MOP / EOP records</h2></div><span className="badge">PROCEDURE GRAPH</span></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({kind:'procedure',projectId:f.get('projectId'),procedureCode:f.get('code'),procedureType:f.get('type'),title:f.get('title'),purpose:f.get('purpose')||undefined,version:f.get('version')||'1.0',status:f.get('status')||'DRAFT',sourceRefs:[]},'Procedure')}}><div style={{...grid,marginTop:12}}><select name="projectId" style={input} required>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="type" style={input} defaultValue="SOP"><option>SOP</option><option>MOP</option><option>EOP</option><option>MAINTENANCE</option><option>LOTO</option><option>COMMISSIONING</option></select><input name="code" placeholder="Procedure code · MOP-ELEC-042" style={input} required/><input name="title" placeholder="Procedure title" style={input} required/><input name="version" defaultValue="1.0" placeholder="Version" style={input}/><select name="status" style={input} defaultValue="DRAFT"><option>DRAFT</option><option>REVIEW</option><option>APPROVED</option></select><input name="purpose" placeholder="Purpose / operating objective" style={{...input,gridColumn:'1 / -1'}}/></div><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Procedure'?'Saving…':'Create Procedure'}</button></div></form>
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Topology</div><h2>Connect STRATUM Assets operationally</h2><p className="muted">These edges power upstream/downstream impact analysis and Procedure Simulation.</p></div></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({kind:'dependency',projectId:f.get('projectId'),sourceAssetId:f.get('source'),targetAssetId:f.get('target'),relationshipType:f.get('relationship'),criticality:f.get('criticality'),sourceRef:{}},'Topology relationship')}}><div style={{...grid,marginTop:12}}><select name="projectId" value={projectId} onChange={e=>setProjectId(e.target.value)} style={input}>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="relationship" style={input} defaultValue="FEEDS"><option>FEEDS</option><option>COOLS</option><option>CONTROLS</option><option>DEPENDS_ON</option><option>PROTECTS</option><option>BYPASSES</option><option>REDUNDANT_TO</option><option>CONNECTED_TO</option></select><select name="source" style={input} required><option value="">Source asset</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><select name="target" style={input} required><option value="">Target asset</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><select name="criticality" style={input} defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Topology relationship'?'Saving…':'Add topology relationship'}</button></div></form>
  </section>

  <section className="card"><div className="section-head"><div><div className="eyebrow">STRATUM Live Iterations</div><h2>Capture near-real-time observed state</h2><p className="muted">State Iterations update operational truth without rewriting the engineering baseline.</p></div><span className="badge">STATE ITERATION</span></div>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({kind:'observation',projectId:f.get('projectId'),assetId:f.get('assetId'),sourceSystem:f.get('sourceSystem'),pointKey:f.get('pointKey'),value:parseValue(String(f.get('value')||'')),quality:f.get('quality'),observedAt:new Date().toISOString()},'Live Observation')}}><div style={{...grid,marginTop:12}}><select name="projectId" value={projectId} onChange={e=>setProjectId(e.target.value)} style={input}>{projects.map(p=><option value={p.id} key={p.id}>{p.projectCode} · {p.name}</option>)}</select><select name="assetId" style={input} required><option value="">Asset</option>{projectAssets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><input name="sourceSystem" placeholder="Source · EPMS / BMS / PLC / DCIM" style={input} required/><input name="pointKey" placeholder="Point · breaker_state / load_pct" style={input} required/><input name="value" placeholder="Value · CLOSED / 73.2 / true" style={input} required/><select name="quality" style={input} defaultValue="GOOD"><option>GOOD</option><option>UNCERTAIN</option><option>BAD</option><option>STALE</option></select></div><div className="button-row"><button className="action" disabled={!!busy}>{busy==='Live Observation'?'Saving…':'Record State Iteration'}</button></div></form>
  </section>
 </div>
}
