'use client';
import {useEffect,useState} from 'react';
import {startAuthentication} from '@simplewebauthn/browser';
import {signPayloadHash} from '@/lib/client/signing';

type Pending={id:string;event_type:string;asset_code:string;asset_name:string;project_code:string;project_name:string;performer_name?:string|null;performer_email?:string|null;performed_by_me:boolean;evidence_count:number;approval_count?:number;approvals_required?:number;payload_sha256:string;allowed_roles?:string[]};
type Session={userId:string;email:string;role:string};
async function json(url:string,options?:RequestInit){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options?.headers||{})}});const x=await r.json();if(!r.ok)throw new Error(x.error||`Request failed (${r.status})`);return x}

export default function PasskeyApprovalQueue(){
 const [items,setItems]=useState<Pending[]>([]),[session,setSession]=useState<Session|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[rejectId,setRejectId]=useState(''),[rejectComment,setRejectComment]=useState('');
 async function refresh(){const x=await json('/api/pending');setItems(x.items||[]);setSession(x.session||null)}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
 function summarize(out:any){return out.status==='AWAITING_APPROVALS'?`Approval recorded · ${out.approvalCount}/${out.approvalsRequired} approvals complete.`:out.status==='REJECTED'?'Lifecycle event rejected.':`Verified in ${out.receipt.network} · DIR #${out.receipt.blockHeight} · ${out.receipt.txHash}`}
 async function approvePasskey(x:Pending){if(x.performed_by_me)return setMessage('Separation of duties: the performer cannot approve this record.');setBusy(`${x.id}:passkey`);setMessage('');try{const options=await json('/api/security/passkeys/assert/options',{method:'POST',body:JSON.stringify({lifecycleEventId:x.id})});const response=await startAuthentication({optionsJSON:options});const verified=await json('/api/security/passkeys/assert/verify',{method:'POST',body:JSON.stringify({lifecycleEventId:x.id,response})});const out=await json('/api/approvals',{method:'POST',body:JSON.stringify({lifecycleEventId:x.id,decision:'APPROVED',comment:'Approved with WebAuthn passkey',passkeyGrant:verified.approvalGrant})});setMessage(summarize(out));await refresh()}catch(e:any){setMessage(`${e.message} You can use the registered browser signing identity as a compatibility fallback.`)}finally{setBusy('')}}
 async function signedDecision(x:Pending,decision:'APPROVED'|'REJECTED',comment:string){if(x.performed_by_me)return setMessage('Separation of duties: the performer cannot decide this record.');if(!session)return setMessage('A signed-in user session is required.');if(decision==='REJECTED'&&!comment.trim())return setMessage('Enter a rejection reason before rejecting the lifecycle event.');setBusy(`${x.id}:${decision}`);setMessage('');try{const signed=await signPayloadHash(session.userId,x.payload_sha256);const out=await json('/api/approvals',{method:'POST',body:JSON.stringify({lifecycleEventId:x.id,decision,comment:comment.trim()||'Approved with registered browser signing identity',signature:signed.signature,signingKeyId:signed.signingKeyId})});setMessage(summarize(out));setRejectId('');setRejectComment('');await refresh()}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 return <section className="card" style={{marginTop:16}}><div className="section-head"><div><div className="eyebrow">4 · Independent Approval</div><h2>Review, approve and finalize</h2><p className="muted">The performer cannot approve the same event. Passkey approval is preferred; a registered P-256 browser signing identity remains available as a compatibility path.</p></div><span className="badge">{items.length} pending</span></div>{message&&<div className="notice" style={{marginTop:12}}><strong>Approval system</strong><span>{message}</span></div>}<div className="timeline" style={{marginTop:12}}>{items.map(x=><div className="event" key={x.id} style={{alignItems:'flex-start'}}><i className="event-icon">{x.evidence_count||0}</i><div style={{flex:1}}><strong>{x.event_type} · {x.asset_code} · {x.asset_name}</strong><small>{x.project_code} · Performed by {x.performer_name||x.performer_email||'Unknown performer'} · evidence {x.evidence_count} · approvals {x.approval_count||0}/{x.approvals_required||1}</small>{x.performed_by_me?<div className="muted" style={{marginTop:8}}>You performed this work; an independent authorized user must decide it.</div>:<><div className="button-row"><button className="action" disabled={!!busy} onClick={()=>approvePasskey(x)}>{busy===`${x.id}:passkey`?'Waiting for passkey…':'Approve with Passkey'}</button><button className="ghost" disabled={!!busy} onClick={()=>signedDecision(x,'APPROVED','')}>{busy===`${x.id}:APPROVED`?'Signing…':'Approve with Browser Key'}</button><button className="ghost" disabled={!!busy} onClick={()=>{setRejectId(rejectId===x.id?'':x.id);setRejectComment('')}}>Reject</button></div>{rejectId===x.id&&<div style={{display:'grid',gap:8,marginTop:10}}><textarea value={rejectComment} onChange={e=>setRejectComment(e.target.value)} placeholder="Required rejection reason" maxLength={1000} style={{width:'100%',minHeight:72,padding:10,borderRadius:10}}/><div><button className="action" disabled={!!busy||!rejectComment.trim()} onClick={()=>signedDecision(x,'REJECTED',rejectComment)}>{busy===`${x.id}:REJECTED`?'Signing rejection…':'Confirm signed rejection'}</button></div></div>}</>}</div></div>)}{!items.length&&<p className="muted">No lifecycle events are waiting for independent approval.</p>}</div></section>
}
