'use client';
import {useEffect,useState} from 'react';
import {getLocalSigner,getOrCreateSigner,revokeAndRotateSigner,removeLocalSigner} from '@/lib/client/signing';
type KeyRow={id:string;label:string;algorithm:string;fingerprint_sha256:string;created_at:string;last_used_at:string|null;revoked_at:string|null};
type Session={userId:string;email:string;role:string};
async function load(){const r=await fetch('/api/security/signing-keys',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load signing keys');return j}
export default function SigningIdentityPanel(){const [keys,setKeys]=useState<KeyRow[]>([]),[session,setSession]=useState<Session|null>(null),[local,setLocal]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){const j=await load();setKeys(j.items||[]);setSession(j.session||null);if(j.session?.userId)setLocal(await getLocalSigner(j.session.userId))}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
 async function ensure(){if(!session)return;setBusy(true);setMessage('');try{const s=await getOrCreateSigner(session.userId);setLocal(s);setMessage(`Signing identity ready: ${s.fingerprint}`);await refresh()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function rotate(){if(!session)return;setBusy(true);setMessage('');try{const s=await revokeAndRotateSigner(session.userId);setLocal(s);setMessage(`Signing identity rotated. New fingerprint: ${s.fingerprint}`);await refresh()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function revoke(k:KeyRow){if(!session)return;setBusy(true);setMessage('');try{const r=await fetch('/api/security/signing-keys',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({keyId:k.id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not revoke signing key');if(local?.keyId===k.id){await removeLocalSigner(session.userId);setLocal(null)}setMessage('Signing key revoked.');await refresh()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 return <div className="grid" style={{gap:16}}>{message&&<div className="card notice"><strong>Identity</strong><span>{message}</span></div>}
  <section className="card"><div className="section-head"><div><div className="eyebrow">Cryptographic Identity</div><h2>{session?.email||'Loading user…'}</h2><p className="muted">Approvals are signed with a persistent P-256 identity registered to your STRATUM account. The private key stays in this browser; the server stores only the public key and its SHA-256 fingerprint.</p></div><span className="badge">{session?.role||'—'}</span></div>
   <div className="grid two" style={{marginTop:16}}><div><div className="label">This browser</div><h3>{local?'Signing key available':'No local signing key'}</h3><p className="mono muted" style={{wordBreak:'break-all'}}>{local?.fingerprint||'A key will be created automatically the first time you approve, or you can create one now.'}</p></div><div className="button-row"><button className="action" disabled={busy||!session} onClick={ensure}>{local?'Confirm identity':'Create signing identity'}</button><button className="ghost" disabled={busy||!session||!local} onClick={rotate}>Rotate key</button></div></div>
  </section>
  <section className="card table-card"><table className="table"><thead><tr><th>Key</th><th>Fingerprint</th><th>Created</th><th>Last used</th><th>Status</th><th>Action</th></tr></thead><tbody>{keys.map(k=><tr key={k.id}><td><strong>{k.label}</strong><div className="muted">{k.algorithm}</div></td><td className="mono" style={{maxWidth:330,wordBreak:'break-all'}}>{k.fingerprint_sha256}</td><td>{new Date(k.created_at).toLocaleString()}</td><td>{k.last_used_at?new Date(k.last_used_at).toLocaleString():'Never'}</td><td><span className={k.revoked_at?'pending':'proof'}>{k.revoked_at?'REVOKED':'ACTIVE'}</span></td><td>{!k.revoked_at&&<button className="ghost" disabled={busy} onClick={()=>revoke(k)}>Revoke</button>}</td></tr>)}{!keys.length&&<tr><td colSpan={6}><div className="muted">No registered signing identities yet.</div></td></tr>}</tbody></table></section>
 </div>}
