import {NextResponse} from 'next/server';
import {z} from 'zod';
import {requireSession} from '@/lib/server/auth';
import {query,tx} from '@/lib/server/db';
import {sha256} from '@/lib/server/hash';
import {verifyApprovalSignature} from '@/lib/server/signature';
import {requireProjectRole} from '@/lib/server/access';
import {appendAudit} from '@/lib/server/audit';
import {verifyApprovalGrant} from '@/lib/server/approval-grant';
import {anchorLifecycleOnce} from '@/lib/server/lifecycle-anchor';
import type {LedgerRecord} from '@/lib/ledger';

const Body=z.object({lifecycleEventId:z.string().uuid(),decision:z.enum(['APPROVED','REJECTED']),comment:z.string().max(1000).optional(),signature:z.string().min(16).optional(),signingKeyId:z.string().uuid().optional(),passkeyGrant:z.string().min(20).optional()}).refine(x=>!!x.passkeyGrant||!!(x.signature&&x.signingKeyId),{message:'A registered signing key signature or verified passkey grant is required'});

export async function POST(req:Request){try{
 const s=await requireSession();const b=Body.parse(await req.json());
 const e=await query<any>(`SELECT le.*,COALESCE(string_agg(ev.sha256,'' ORDER BY ev.sha256),'') evidence_concat,COUNT(ev.id)::int evidence_count FROM lifecycle_events le LEFT JOIN evidence ev ON ev.lifecycle_event_id=le.id WHERE le.id=$1 AND le.organization_id=$2 GROUP BY le.id`,[b.lifecycleEventId,s.organizationId]);
 const event=e.rows[0];if(!event)return NextResponse.json({error:'Lifecycle event not found'},{status:404});
 if(event.status==='VERIFIED')return NextResponse.json({status:'VERIFIED',receipt:{network:event.ledger_network,txHash:event.ledger_tx_hash,blockHeight:event.ledger_block_height,timestamp:event.anchored_at}});
 if(event.status==='REJECTED')return NextResponse.json({error:'This lifecycle event has already been rejected.'},{status:409});
 const approverRole=await requireProjectRole(s,event.project_id,['SUPER_ADMIN','ORG_ADMIN','PROJECT_MANAGER','INSPECTOR']);
 if(event.performed_by===s.userId)return NextResponse.json({error:'Separation of duties: performer cannot approve the same lifecycle event.'},{status:409});
 const policyResult=await query<any>(`SELECT * FROM approval_policies WHERE organization_id=$1 AND project_id=$2 AND is_active=true LIMIT 1`,[s.organizationId,event.project_id]);
 const policy=policyResult.rows[0]||{id:null,approvals_required:1,allowed_roles:['INSPECTOR','PROJECT_MANAGER','ORG_ADMIN','SUPER_ADMIN'],require_evidence:true};
 if(!policy.allowed_roles.includes(approverRole))return NextResponse.json({error:`Project role ${approverRole} is not permitted by this project's approval policy.`},{status:403});
 if(policy.require_evidence&&Number(event.evidence_count||0)<1)return NextResponse.json({error:'This project requires at least one evidence item before approval.'},{status:409});

 let authMethod='P256_BROWSER_KEY',signerFingerprint:string|null=null,signingKey:any=null,webauthnCredentialId:string|null=null,signature:string|null=null,publicKeyJwk:any=null,signatureAlgorithm:string|null=null;
 if(b.passkeyGrant){const g=await verifyApprovalGrant(b.passkeyGrant);if(g.userId!==s.userId||g.organizationId!==s.organizationId||g.lifecycleEventId!==event.id||g.payloadHash!==event.payload_sha256)return NextResponse.json({error:'Passkey approval grant does not match this lifecycle record.'},{status:422});const c=await query<any>(`SELECT id,credential_id FROM webauthn_credentials WHERE id=$1 AND organization_id=$2 AND user_id=$3 AND revoked_at IS NULL LIMIT 1`,[g.credentialDbId,s.organizationId,s.userId]);if(!c.rows[0]||c.rows[0].credential_id!==g.credentialId)return NextResponse.json({error:'Passkey is no longer active.'},{status:422});authMethod='WEBAUTHN_PASSKEY';webauthnCredentialId=c.rows[0].id;signerFingerprint=sha256(`webauthn:${g.credentialId}`);signatureAlgorithm='WEBAUTHN_ASSERTION';}
 else{const k=await query<{id:string;public_key_jwk:JsonWebKey;fingerprint_sha256:string;algorithm:string}>(`SELECT id,public_key_jwk,fingerprint_sha256,algorithm FROM user_signing_keys WHERE id=$1 AND organization_id=$2 AND user_id=$3 AND revoked_at IS NULL LIMIT 1`,[b.signingKeyId,s.organizationId,s.userId]);signingKey=k.rows[0];if(!signingKey)return NextResponse.json({error:'Registered active signing key not found for this user.'},{status:422});if(!verifyApprovalSignature(event.payload_sha256,b.signature!,signingKey.public_key_jwk))return NextResponse.json({error:'Approval signature could not be verified against the registered signing identity.'},{status:422});signerFingerprint=signingKey.fingerprint_sha256;signature=b.signature!;publicKeyJwk=signingKey.public_key_jwk;signatureAlgorithm=signingKey.algorithm;}

 const evidenceHash=sha256(event.evidence_concat||'');
 const insertApproval=async(c:any,decision:'APPROVED'|'REJECTED')=>c.query(`INSERT INTO approvals(organization_id,lifecycle_event_id,approver_user_id,decision,comment,signature,public_key_jwk,signing_key_id,signature_algorithm,signer_fingerprint_sha256,approval_policy_id,sequence_number,auth_method,webauthn_credential_id) SELECT $1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,COALESCE(MAX(sequence_number),0)+1,$12,$13 FROM approvals WHERE lifecycle_event_id=$2 ON CONFLICT(lifecycle_event_id,approver_user_id) WHERE decision='APPROVED' DO NOTHING`,[s.organizationId,b.lifecycleEventId,s.userId,decision,b.comment||null,signature,publicKeyJwk?JSON.stringify(publicKeyJwk):null,signingKey?.id||null,signatureAlgorithm,signerFingerprint,policy.id,authMethod,webauthnCredentialId]);
 if(b.decision==='REJECTED'){
  await tx(async c=>{await c.query(`SELECT pg_advisory_xact_lock(hashtext($1))`,[`approval:${b.lifecycleEventId}`]);const current=await c.query(`SELECT status FROM lifecycle_events WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[b.lifecycleEventId,s.organizationId]);if(current.rows[0]?.status==='VERIFIED')throw Object.assign(new Error('Verified lifecycle event cannot be rejected'),{status:409});if(current.rows[0]?.status==='REJECTED')return;await insertApproval(c,'REJECTED');if(signingKey)await c.query(`UPDATE user_signing_keys SET last_used_at=now() WHERE id=$1`,[signingKey.id]);await c.query(`UPDATE lifecycle_events SET status='REJECTED',approved_by=$1 WHERE id=$2 AND organization_id=$3`,[s.userId,b.lifecycleEventId,s.organizationId])});
  await appendAudit({organizationId:s.organizationId,actorUserId:s.userId,action:'LIFECYCLE_REJECT',entityType:'LIFECYCLE_EVENT',entityId:b.lifecycleEventId,metadata:{projectId:event.project_id,authMethod,signerFingerprint,policyId:policy.id,approverRole}});
  return NextResponse.json({status:'REJECTED',authMethod,signerFingerprint});
 }
 const approvalState=await tx(async c=>{await c.query(`SELECT pg_advisory_xact_lock(hashtext($1))`,[`approval:${b.lifecycleEventId}`]);const current=await c.query(`SELECT status FROM lifecycle_events WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[b.lifecycleEventId,s.organizationId]);if(current.rows[0]?.status==='REJECTED')throw Object.assign(new Error('Rejected lifecycle event cannot be approved'),{status:409});await insertApproval(c,'APPROVED');if(signingKey)await c.query(`UPDATE user_signing_keys SET last_used_at=now() WHERE id=$1`,[signingKey.id]);const count=await c.query<{n:number}>(`SELECT COUNT(DISTINCT approver_user_id)::int n FROM approvals WHERE lifecycle_event_id=$1 AND decision='APPROVED'`,[b.lifecycleEventId]);return{count:count.rows[0]?.n||0,required:Number(policy.approvals_required||1),alreadyVerified:current.rows[0]?.status==='VERIFIED'}});
 await appendAudit({organizationId:s.organizationId,actorUserId:s.userId,action:'LIFECYCLE_APPROVAL_RECORDED',entityType:'LIFECYCLE_EVENT',entityId:b.lifecycleEventId,metadata:{projectId:event.project_id,approvalCount:approvalState.count,approvalsRequired:approvalState.required,authMethod,signerFingerprint,policyId:policy.id,approverRole}});
 if(approvalState.alreadyVerified){const current=await query<any>(`SELECT ledger_network,ledger_tx_hash,ledger_block_height,anchored_at FROM lifecycle_events WHERE id=$1 AND organization_id=$2`,[b.lifecycleEventId,s.organizationId]);const x=current.rows[0];return NextResponse.json({status:'VERIFIED',receipt:{network:x.ledger_network,txHash:x.ledger_tx_hash,blockHeight:x.ledger_block_height,timestamp:x.anchored_at},approvalCount:approvalState.count,approvalsRequired:approvalState.required,authMethod,signerFingerprint})}
 if(approvalState.count<approvalState.required)return NextResponse.json({status:'AWAITING_APPROVALS',approvalCount:approvalState.count,approvalsRequired:approvalState.required,authMethod,signerFingerprint});
 const record:LedgerRecord={organizationId:s.organizationId,projectId:event.project_id,assetId:event.asset_id,recordId:event.id,type:event.event_type,evidenceHash,timestamp:event.occurred_at.toISOString(),signer:`policy:${policy.id||'default'}:approvals:${approvalState.count}`,payloadHash:event.payload_sha256};
 const finalized=await anchorLifecycleOnce({organizationId:s.organizationId,lifecycleEventId:b.lifecycleEventId,approvedBy:s.userId,evidenceHash,record});const receipt=finalized.receipt;
 if(!finalized.alreadyFinalized)await appendAudit({organizationId:s.organizationId,actorUserId:s.userId,action:'LIFECYCLE_APPROVAL_THRESHOLD_ANCHOR',entityType:'LIFECYCLE_EVENT',entityId:b.lifecycleEventId,metadata:{projectId:event.project_id,approvalCount:approvalState.count,approvalsRequired:approvalState.required,network:receipt.network,txHash:receipt.txHash,blockHeight:receipt.blockHeight,policyId:policy.id}});
 return NextResponse.json({status:'VERIFIED',receipt,evidenceHash,approvalCount:approvalState.count,approvalsRequired:approvalState.required,authMethod,signerFingerprint,alreadyFinalized:finalized.alreadyFinalized});
}catch(e:any){return NextResponse.json({error:e.message},{status:e.status||400})}}
