import {NextResponse} from 'next/server';
import {z} from 'zod';
import {requireSession,revokeAllSessions,SessionRole} from '@/lib/server/auth';
import {query,tx} from '@/lib/server/db';

const Role=z.enum(['SUPER_ADMIN','ORG_ADMIN','PROJECT_MANAGER','TECHNICIAN','CLIENT','INSPECTOR','VIEWER']);
const Create=z.object({email:z.string().email(),displayName:z.string().min(2).max(160),role:Role,password:z.string().min(12).max(200)});
const Patch=z.object({userId:z.string().uuid(),role:Role.optional(),isActive:z.boolean().optional(),displayName:z.string().min(2).max(160).optional(),resetSessions:z.boolean().optional()});

export async function GET(){try{const s=await requireSession(['SUPER_ADMIN','ORG_ADMIN']);const r=await query(`SELECT u.id,u.email,u.display_name,u.is_active,u.last_login_at,u.created_at,m.role,u.session_version,COUNT(k.id) FILTER(WHERE k.revoked_at IS NULL)::int active_signing_keys FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN user_signing_keys k ON k.user_id=u.id AND k.organization_id=m.organization_id WHERE m.organization_id=$1 GROUP BY u.id,m.role ORDER BY u.display_name,u.email`,[s.organizationId]);return NextResponse.json({items:r.rows,session:s})}catch(e:any){return NextResponse.json({error:e.message},{status:e.status||500})}}

export async function POST(req:Request){try{const s=await requireSession(['SUPER_ADMIN','ORG_ADMIN']);const b=Create.parse(await req.json());if(b.role==='SUPER_ADMIN'&&s.role!=='SUPER_ADMIN')return NextResponse.json({error:'Only a SUPER_ADMIN can create another SUPER_ADMIN'},{status:403});const out=await tx(async c=>{const u=await c.query(`INSERT INTO users(email,display_name,password_hash,is_active,last_password_change_at) VALUES($1,$2,crypt($3,gen_salt('bf')),true,now()) ON CONFLICT(email) DO UPDATE SET display_name=EXCLUDED.display_name RETURNING id,email,display_name,is_active`,[b.email,b.displayName,b.password]);const user=u.rows[0];await c.query(`INSERT INTO memberships(organization_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(organization_id,user_id) DO UPDATE SET role=EXCLUDED.role`,[s.organizationId,user.id,b.role]);await c.query(`INSERT INTO audit_log(organization_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'USER_CREATE_OR_INVITE','USER',$3,$4::jsonb)`,[s.organizationId,s.userId,user.id,JSON.stringify({email:b.email,role:b.role})]);return{...user,role:b.role}});return NextResponse.json(out,{status:201})}catch(e:any){return NextResponse.json({error:e.message},{status:e.status||400})}}

export async function PATCH(req:Request){try{const s=await requireSession(['SUPER_ADMIN','ORG_ADMIN']);const b=Patch.parse(await req.json());if(b.userId===s.userId&&b.isActive===false)return NextResponse.json({error:'You cannot disable your own account.'},{status:409});const current=await query<{role:SessionRole}>(`SELECT role FROM memberships WHERE organization_id=$1 AND user_id=$2`,[s.organizationId,b.userId]);if(!current.rows[0])return NextResponse.json({error:'User not found in this organization'},{status:404});if((current.rows[0].role==='SUPER_ADMIN'||b.role==='SUPER_ADMIN')&&s.role!=='SUPER_ADMIN')return NextResponse.json({error:'SUPER_ADMIN membership can only be managed by a SUPER_ADMIN'},{status:403});await tx(async c=>{if(b.displayName!==undefined)await c.query(`UPDATE users SET display_name=$1 WHERE id=$2`,[b.displayName,b.userId]);if(b.isActive!==undefined)await c.query(`UPDATE users SET is_active=$1,session_version=CASE WHEN $1=false THEN session_version+1 ELSE session_version END WHERE id=$2`,[b.isActive,b.userId]);if(b.role!==undefined)await c.query(`UPDATE memberships SET role=$1 WHERE organization_id=$2 AND user_id=$3`,[b.role,s.organizationId,b.userId]);await c.query(`INSERT INTO audit_log(organization_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'USER_UPDATE','USER',$3,$4::jsonb)`,[s.organizationId,s.userId,b.userId,JSON.stringify({role:b.role,isActive:b.isActive,displayName:b.displayName,resetSessions:b.resetSessions})])});if(b.resetSessions)await revokeAllSessions(b.userId,s.organizationId,s.userId);return NextResponse.json({ok:true})}catch(e:any){return NextResponse.json({error:e.message},{status:e.status||400})}}
