import {NextResponse} from 'next/server';
import {z} from 'zod';
import {requireSession} from '@/lib/server/auth';
import {query} from '@/lib/server/db';
import {accessibleProjectIds,requireProjectRole} from '@/lib/server/access';
import {appendAudit} from '@/lib/server/audit';
const Body=z.object({siteId:z.string().uuid(),parentSystemId:z.string().uuid().optional().nullable(),name:z.string().min(2).max(180),systemType:z.string().max(120).optional()});
export async function GET(){try{const s=await requireSession();const ids=await accessibleProjectIds(s);if(!ids.length)return NextResponse.json({items:[]});const r=await query(`SELECT sy.*,si.name site_name,p.name project_name,p.id project_id FROM systems sy JOIN sites si ON si.id=sy.site_id JOIN projects p ON p.id=si.project_id WHERE sy.organization_id=$1 AND p.id=ANY($2::uuid[]) ORDER BY sy.created_at DESC`,[s.organizationId,ids]);return NextResponse.json({items:r.rows})}catch(e:any){return NextResponse.json({error:e.message},{status:e.status||500})}}
export async function POST(req:Request){try{const s=await requireSession();const b=Body.parse(await req.json());const site=await query<{project_id:string}>(`SELECT project_id FROM sites WHERE id=$1 AND organization_id=$2 LIMIT 1`,[b.siteId,s.organizationId]);if(!site.rows[0])return NextResponse.json({error:'Site is not available in the active organization.'},{status:403});const effectiveRole=await requireProjectRole(s,site.rows[0].project_id,['SUPER_ADMIN','ORG_ADMIN','PROJECT_MANAGER']);if(b.parentSystemId){const parent=await query(`SELECT id FROM systems WHERE id=$1 AND organization_id=$2 AND site_id=$3 LIMIT 1`,[b.parentSystemId,s.organizationId,b.siteId]);if(!parent.rows[0])return NextResponse.json({error:'Parent system is not available on this site.'},{status:403})}const r=await query(`INSERT INTO systems(organization_id,site_id,parent_system_id,name,system_type) VALUES($1,$2,$3,$4,$5) RETURNING *`,[s.organizationId,b.siteId,b.parentSystemId||null,b.name,b.systemType||null]);await appendAudit({organizationId:s.organizationId,actorUserId:s.userId,action:'SYSTEM_CREATE',entityType:'SYSTEM',entityId:r.rows[0].id,metadata:{projectId:site.rows[0].project_id,siteId:b.siteId,name:b.name,systemType:b.systemType||null,effectiveRole}});return NextResponse.json(r.rows[0],{status:201})}catch(e:any){return NextResponse.json({error:e.message},{status:e.status||400})}}
