import {notFound} from 'next/navigation';
import Link from 'next/link';
import AssetQR from '@/components/AssetQR';
import {assetLifecycle,liveAsset,publicEvidence} from '@/lib/server/live-views';
export const dynamic='force-dynamic';
const date=(d:Date|string|null)=>d?new Date(d).toLocaleString('en-US',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const short=(s:string|null,n=18)=>s?s.length>n*2?`${s.slice(0,n)}…${s.slice(-n)}`:s:'—';
export default async function AssetDetail({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const asset=await liveAsset(decodeURIComponent(id));if(!asset)notFound();
 const [events,evidence]=await Promise.all([assetLifecycle(asset.id),publicEvidence(asset.id)]);
 const qr=`https://stratum-verified.vercel.app/verify?q=${encodeURIComponent(asset.asset_code)}`;
 return <><div className="page-head"><div><div className="eyebrow">Live Asset Passport · {asset.asset_code}</div><h1 className="title">{asset.name}</h1><p className="subtitle">{asset.manufacturer_name||'Manufacturer pending'} {asset.model||''} · Serial {asset.serial_number||'—'}</p></div><div className="button-row"><Link className="ghost" href={`/verify?q=${encodeURIComponent(asset.asset_code)}`}>Public verify</Link><Link className="action" href="/workflows">+ Lifecycle event</Link></div></div>
 <section className="grid asset-top"><div className="card"><div className="asset-identity"><div><span className="status-chip">{asset.status}</span><h2>{asset.system_name||'System unassigned'}</h2><p className="muted">{asset.project_name} · {asset.site_name} · {asset.location_label||'Location pending'}</p></div><div className="qr-wrap"><AssetQR value={qr} size={150}/><small>{asset.asset_code}</small></div></div><div className="spec-grid">{Object.entries(asset.specifications||{}).map(([k,v])=><div key={k}><span>{k}</span><strong>{typeof v==='string'?v:JSON.stringify(v)}</strong></div>)}<div><span>Installed</span><strong>{date(asset.installed_at)}</strong></div><div><span>Commissioned</span><strong>{date(asset.commissioned_at)}</strong></div><div><span>Warranty through</span><strong>{date(asset.warranty_expires_at)}</strong></div></div></div>
 <div className="card proof-panel"><div className="eyebrow">Latest Immutable Proof</div>{asset.ledger_block_height?<><div className="proof-seal">✓</div><h2>Verified on STRATUM Chain</h2><div className="proof-data"><span>Network</span><b>{asset.ledger_network||'stratum-devnet-1'}</b><span>Block</span><b>#{asset.ledger_block_height}</b><span>Transaction</span><b className="mono" title={asset.ledger_tx_hash||''}>{short(asset.ledger_tx_hash)}</b><span>Record</span><b className="mono">{short(asset.latest_event_id)}</b><span>Anchored</span><b>{date(asset.anchored_at)}</b></div></>:<><div className="proof-seal pending-seal">…</div><h2>Awaiting verified lifecycle event</h2><p className="muted">Approved evidence packages will appear here after validator quorum finalizes the record.</p></>}</div></section>
 <section className="card lifecycle-card"><div className="section-head"><div><div className="eyebrow">Lifecycle</div><h2>Verified history</h2></div><span className="proof">{events.filter((e:any)=>e.status==='VERIFIED').length} verified</span></div><div className="vertical-timeline">{events.map((e:any)=><div className={`life-event ${e.status==='VERIFIED'?'verified':e.status==='SUBMITTED'?'pending':''}`} key={e.id}><i>{e.status==='VERIFIED'?'✓':e.status==='SUBMITTED'?'●':'○'}</i><div><strong>{e.event_type}</strong><span>{date(e.occurred_at)} · {e.performed_by_name||'Actor recorded'}{e.approved_by_name?` → approved by ${e.approved_by_name}`:''}</span><small className="mono">Payload {short(e.payload_sha256,14)} · Evidence {short(e.evidence_package_sha256,14)}</small></div><b>{e.ledger_block_height?`Block ${e.ledger_block_height}`:e.status}</b></div>)}{!events.length&&<p className="muted">No lifecycle events recorded yet.</p>}</div></section>
 <section className="grid two"><div className="card"><div className="section-head"><div><div className="eyebrow">Evidence fingerprints</div><h3>Off-chain files, on-chain integrity</h3></div></div>{evidence.length?evidence.map((d:any)=><div className="file-row" key={d.id}><div className="file-icon">SHA</div><div><strong>{d.kind}</strong><small>SHA-256 <span className="mono">{short(d.sha256,16)}</span> · {date(d.captured_at)}</small></div><span className="proof">{d.visibility}</span></div>):<p className="muted">No evidence linked yet.</p>}<p className="muted">Private file contents are not exposed by this passport; only verification metadata and cryptographic fingerprints are shown.</p></div><div className="card"><div className="eyebrow">Provenance</div><h3>Asset context</h3><div className="custody"><div><i/>Project<span>{asset.project_code} · {asset.project_name}</span></div><div><i/>Physical site<span>{asset.site_name}</span></div><div><i/>Electrical system<span>{asset.system_name||'Unassigned'}</span></div><div><i/>Equipment identity<span>{asset.asset_code} · {asset.serial_number||'No serial'}</span></div><div><i/>STRATUM Chain<span>{asset.ledger_block_height?`Finalized at Block ${asset.ledger_block_height}`:'Awaiting first proof'}</span></div></div></div></section></>;
}