export type Role='SUPER_ADMIN'|'ORG_ADMIN'|'PROJECT_MANAGER'|'TECHNICIAN'|'CLIENT'|'INSPECTOR'|'VIEWER';
export type Permission='ORG_MANAGE'|'SITE_WRITE'|'ASSET_WRITE'|'WORK_ORDER_WRITE'|'EVENT_CREATE'|'EVENT_APPROVE'|'EVIDENCE_UPLOAD'|'VIEW_PRIVATE'|'VERIFY_PUBLIC';
const grants:Record<Role,Permission[]>={
  SUPER_ADMIN:['ORG_MANAGE','SITE_WRITE','ASSET_WRITE','WORK_ORDER_WRITE','EVENT_CREATE','EVENT_APPROVE','EVIDENCE_UPLOAD','VIEW_PRIVATE','VERIFY_PUBLIC'],
  ORG_ADMIN:['ORG_MANAGE','SITE_WRITE','ASSET_WRITE','WORK_ORDER_WRITE','EVENT_CREATE','EVENT_APPROVE','EVIDENCE_UPLOAD','VIEW_PRIVATE','VERIFY_PUBLIC'],
  PROJECT_MANAGER:['SITE_WRITE','ASSET_WRITE','WORK_ORDER_WRITE','EVENT_CREATE','EVENT_APPROVE','EVIDENCE_UPLOAD','VIEW_PRIVATE','VERIFY_PUBLIC'],
  TECHNICIAN:['EVENT_CREATE','EVIDENCE_UPLOAD','VIEW_PRIVATE','VERIFY_PUBLIC'],
  CLIENT:['VIEW_PRIVATE','VERIFY_PUBLIC'],
  INSPECTOR:['EVENT_CREATE','EVENT_APPROVE','EVIDENCE_UPLOAD','VIEW_PRIVATE','VERIFY_PUBLIC'],
  VIEWER:['VERIFY_PUBLIC']
};
export const can=(role:Role,permission:Permission)=>grants[role].includes(permission);
